### ISSUE TITLE
Fail to build on hosts with openssl 1.1.1

### ISSUE THREAD

**Issue by b-zee** [maidsafe/crust#1012]
I've encountered the exact following issue while building crust from source: https://github.com/sfackler/rust-openssl/issues/994

OS: Arch Linux (Raspberry Pi)

Not sure whether this is something that can be fixed in the dependency files etc. I'm not familiar with the build environment of Rust.

**Comment by ustulation** [comment]
This is probably from rust_sodium. See if you can build [rust_sodium](https://github.com/maidsafe/rust_sodium) master currently as that has been fixed there i think. Crust will soon use [safe_crypto](https://github.com/maidsafe/safe_crypto) and this should hopefully be resolved anyway.

**Comment by ustulation** [comment]
Closing this as i suspect the issue is solved and also due to no response.

**Comment by b-zee** [comment]
Sorry for not responding to this. Back when I made the issue I didn't understand Rust enough to look into it.

If I get this right: The issue is solved in newer versions of `rust_sodium` as the `reqwest` dependency was changed to `http_req` which leads to an updated version of the `openssl` crate that fixes linkage to OpenSSL 1.1.
