### ISSUE TITLE
Dashboard performance slowed the more results received. 

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1013]
Move the computation logic to a web worker so that the UI is not blocking. Redux provides couple of options to pick. Pick one of the modules which integrates well for our use case.

**Comment by nadiaburborough** [comment]
<img width="1217" alt="screen shot 2018-10-17 at 9 14 35 pm" src="https://user-images.githubusercontent.com/35568923/47142495-e571f180-d2ba-11e8-9cdd-ecdf6c4ee50b.png">

**Comment by nadiaburborough** [comment]
Krishna investigating - thread computation, web socket connection handling.

**Comment by S-Coyle** [comment]
Results with 20,000 records on the dashboard after all optimisation & local cache storage implemented:
Chrome 1st load = 23 secs
Chrome 2nd load = 17 secs
FF 1st load = 23 secs
FF 2nd load = 18 secs
Safari 1st load = 15 secs
Safari 2nd load = 13 secs

Reports of adding/removing filters taking up to 10 seconds to load results - I typically get < 6 seconds.

No success criteria was agreed at planning - are we happy with this? If so we can test again with 10,000 to ensure the load time drops

**Comment by nadiaburborough** [comment]
@S-Coyle to retest with 10,000 records and record results

**Comment by S-Coyle** [comment]
Further performance enhancements added - speed now <10 seconds for 10,000 records on Chrome, Safari & FF, and < 5 seconds for refreshes and filter additions/removals
