### ISSUE TITLE
Make it clear that Dashboard results are not specific to current user’s runs.

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1014]
Forum member comment:
📮  https://safenetforum.org/t/crust-test-nat-traversal-join-the-live-test/25799/33

--- 

Possible solution:
🗒 Suggest changing the dashboard text in the topic to make it clear:

> The [Crust Dashboard](https://crusttest.maidsafe.net/) shows you the _global_ results of the test so far and lets you get a feel for hole-punched peer-to-peer connections that are being made.  
> 
> This will be across a range of geographic locations, NAT (router) types and operating systems which will be displayed.  
>
> We are planning on adding the ability to filter dashboard results by your own client connections but currently the figures are for global connection attempts.

**Comment by david-maidsafe** [comment]
Added possible solution (text) to the issue.

**Comment by david-maidsafe** [comment]
Added text to forum post
