### ISSUE TITLE
Clarify cookies use on the dashboard

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/crust#1015]
Issue title says it all.
---
🗒 Possible solution - add the following text to the Forum post

> ### Cookies
> The invite server (`crusttest.maidsafe.net`) creates a single cookie once the user has authenticated themselves using their forum account.  The cookie contains the following information:
> - Session ID

**Comment by nadiaburborough** [comment]
Necessary for the dashboard, but need to communicate this out.

**Comment by nadiaburborough** [comment]
Krishna to give David a list of Cookies in use
David to update the forum post

**Comment by david-maidsafe** [comment]
I _think_ ... It's the invite server rather than the dashboard... although they share the same server so can be considered the same.

Possible text solution added to description.

**Comment by david-maidsafe** [comment]
added text to forum post!
