### ISSUE TITLE
GLIBC_2.25 not found

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1016]
https://safenetforum.org/t/crust-test-nat-traversal-join-the-live-test/25799/18?u=nadia 

https://safenetforum.org/t/crust-test-nat-traversal-join-the-live-test/25799/47?u=nadia

https://safenetforum.org/t/crust-test-nat-traversal-join-the-live-test/25799/61?u=nadia

**Comment by nbaksalyar** [comment]
This has been resolved by building with `musl`.

**Comment by S-Coyle** [comment]
No reports in forum after v2 release of this issue - closing
