### ISSUE TITLE
Error on mac mini - couldn't connect

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1018]
https://safenetforum.org/t/crust-test-nat-traversal-join-the-live-test/25799/83?u=nadia

**Comment by nadiaburborough** [comment]
my best guess so far is that the binary compiled on Mojave is incompatible with High Sierra in some ways. We have a similar Mac Mini machine that runs High Sierra too, so we’ll try to test it there first thing in the morning (https://safenetforum.org/t/crust-test-nat-traversal-join-the-live-test/25799/93?u=nadia)

**Comment by nbaksalyar** [comment]
This should have been resolved by moving the builds to Travis CI.

**Comment by S-Coyle** [comment]
No reports of this issue after v2 release - resolving
