### ISSUE TITLE
Duplication of a connected endpoint causes both connections to be dropped

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#102]
The fault can be found by running two instances of the crust_node example.  The second node should be connected to the first's listening endpoint.  If you then try and connect again from the second node to the first's listener, the connection is briefly established, but then both the original connection and the new one are dropped.

I believe this is down to a misunderstanding of how [`HashMap::insert`](http://doc.rust-lang.org/std/collections/struct.HashMap.html#method.insert) works.  I had wrongly assumed (despite reading the docs) that it would behave similarly to the C++ equivalent, but it doesn't.  It returns the value which was previously there and replaces it with the new value.

We keep a `HashMap` of channels, indexed by endpoint.  So when the second attempt to insert the same endpoint happens, we get the original channel returned and replace it with the new one.  We ignore the return value of the `insert` using `let _ = `, so the original channel is almost immediately destroyed.

This causes that channel's reader thread to break out of its loop, reporting "receiving on a closed channel".  When the loop exits, we unregister that endpoint - i.e. we remove that entry from the `HashMap`.  However, the HashMap now contains the new channel at that endpoint, so when we remove the entry, we destroy the new channel too, causing both TCP connections to be dropped.

**Comment by dirvine** [comment]
Ok cool, if we can then implement it using a container that is better suited or use HashMap slightly differently (check then insert) or similar then I am happy. It is an implementation issue by looks of it. So if we can make the change and also have a test to confirm this is doing what we want then all good.
