### ISSUE TITLE
Add FAQ to explain dashboard duplication rules

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/crust#1025]
Require a new FAQ to explain how the dashboard interprets duplicate results.
---
Possible solution:
> ### Duplicate results
> If multiple clients are run from the exact same environments (same IP Address, Operating System, NAT Type, TCP HP Result & UDP HP Result) then the results will be considered a duplicate and the results will be ignored. This is also true if the peer_requester and peer_responder have been swapped. If the clients have any differences in their environments then the results will not be considered duplicates and will be recorded.

**Comment by david-maidsafe** [comment]
added possible text solution

**Comment by david-maidsafe** [comment]
Changed text on Forum post
