### ISSUE TITLE
Implement direct connections in the client

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/crust#1027]
1. Make use of functions already present in Crust (`prepare_connection_info` and `connect`) and attempt to connect directly or with the use of IGD.
1. Wait for all connections results before sending a log to the proxy (i.e. if we collected hole punching results first then wait for direct conn. result, or vice versa).
1. THIS IS WRONG (don't do this pls): ~Do _not_ attempt direct connections if we detected that UPnP is not available _and_ the IP address is not global.~
1. Make sure the NAT traversal features of Crust are turned off (which is the [default case](https://docs.rs/crust/0.31.0/src/crust/main/service.rs.html#38)).
1. If peer ip is local at the just log Local <-> Local instead of IPs for TCP direct connection result. If global then do the usual <EP-peer0> <-> <EP-peer1> (just like what you do for the holepunch success result).

**Comment by S-Coyle** [comment]
Tested & implemented successfully
