### ISSUE TITLE
Change JSON format send to the dashboard

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/crust#1028]
The main JSON structure sent to the proxy is the following:

```rust
pub struct LogEntry {
    peer_requester: Peer,
    peer_responder: Peer,
    udp_hole_punch_result: NatTraversalResult,
    tcp_hole_punch_result: NatTraversalResult,
    is_direct_successful: bool,
}
```

Notice that `is_direct_successful: bool` has been be added.
It will be represented as-is in JSON (i.e. just `is_direct_sucessful: true/false`).

And the Peer struct is now defined as follows:

```rust
pub struct Peer {
    pub id: [u8; 32],
    pub name: Option<String>,
    pub ip: Ipv4Addr,
    pub nat_type: NatType,
    pub os: String,
}
```

The changes here are the added `id` and `name` fields.

In JSON it will be represented as an array for ID (id: `[1, 2, 3, ...]`) and for name it's either `null` (when a user didn't set their name) or a string (`name: "Abc"`).

**Comment by S-Coyle** [comment]
Implemented & tested successfully
