### ISSUE TITLE
Send a history of NAT type changes to the proxy

### ISSUE THREAD

**Issue by ustulation** [maidsafe/crust#1032]
1. Currently, we send only the initially detected NAT type and log all the NAT type changes on the client side only. For this we store `NatInfo` struct (containing both TCP and UDP NAT types) on the client side and compare it against the `NatInfo` that comes from p2p. The comparison involves a custom implementation of `PartialEq` that does not account for the extra info (such as EDM-Random port numbers). If the stored `NatInfo` is different from the one that we get from p2p, we print out the 'changed NAT type' log.
1. Once the NAT type change happens, instead of just logging it, also send an RPC to the proxy that should indicate the new detected NAT type (for both TCP and UDP).
1. On the proxy side log the NAT type changes for each client as `(peer_id, udp_nat_type, tcp_nat_type)`

**Comment by S-Coyle** [comment]
Tested & implemented successfully
