### ISSUE TITLE
"null" displayed on Dashboard if user name left blank

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/crust#1037]
![image](https://user-images.githubusercontent.com/37112040/47507720-9c95dc00-d86a-11e8-86e4-8fd66a437006.png)

Not sure if this is the best way to display a blank name

**Comment by nadiaburborough** [comment]
Null to be changed to 'anon'

**Comment by nadiaburborough** [comment]
Test as a blank then decide on the change.
