### ISSUE TITLE
DG successfully HP connected to his previously terminated session according to dashboard...

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/crust#1038]
David's steps today:
- ran the osx app with username DavidGeddes
- Disconnected a few times (3 I think) and relaunched the app under different usernames - these would all of course be duplicates as far as the dashboard is concerned
- Disconnected again when he came downstairs (therefore IP address change) and reconnected with no username - this has lef to him connecting successfully to his 1st session from earlier

![image](https://user-images.githubusercontent.com/37112040/47509844-d7017800-d86e-11e8-8e48-9975e03c04f0.png)

**Comment by nadiaburborough** [comment]
Unable to be reproduced

**Comment by S-Coyle** [comment]
Closing as unable to reproduce this in the various stages of internal testing, or in v2 production
