### ISSUE TITLE
Success rate is only shown in the pie chart for 1% or above

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1040]
Successful is 43 but the success rate is still showing 0% - prob because it's 0.0044% success.
Are we ok with this?

**Comment by nadiaburborough** [comment]
<img width="576" alt="screen shot 2018-10-25 at 3 45 35 pm" src="https://user-images.githubusercontent.com/35568923/47509230-935a3e80-d86d-11e8-97d0-8c4111cda2ac.png">

**Comment by nadiaburborough** [comment]
The % in the middle functions correctly - it rounds to the nearest whole number. Therefore 0% for 46/9726 results displays correctly. Expectation is more than 1% of connections will succeed therefore this won't be an issue.

**Comment by shankar2105** [comment]
@nadiaburborough displaying 0% to the user is like there is no connection. How about showing it as `<1%` instead of `0%`

**Comment by S-Coyle** [comment]
No longer required
