### ISSUE TITLE
Need to include cookie consent notice on https://crusttest.maidsafe.net/auth.html

### ISSUE THREAD

**Issue by JimCollinson** [maidsafe/crust#1044]
As per this thread: https://maidsafe.slack.com/archives/CCPT6B1A5/p1540391843000100?thread_ts=1540370870.000100&cid=CCPT6B1A5

Confirm final text with @dgeddes

**Comment by nadiaburborough** [comment]
included on page - for @victoriarussell to sign off on

**Comment by nadiaburborough** [comment]
@victoriarussell has approved.
