### ISSUE TITLE
Filter By User only works if I search lower case

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/crust#1045]
MacOS High Sierra 10.13.6.
Chrome - 68.0.3440.106 (Official Build) (64-bit)

Only works if I search with everything lower case, e.g. "Stephen" returns no results, while "stephen" does, despite Stephen having an uppercase "S" in the results.

**Comment by ashwinkumar6** [comment]
@S-Coyle 
other issues fixed wrt this
- Clear the list displayed if component goes out of focus
(user types on search bar, clicks outside the listbox and click inside again, the previous suggested list is displayed)
