### ISSUE TITLE
Pie chart and table mobile viewport issues

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/crust#1051]
![image](https://user-images.githubusercontent.com/37112040/47554303-f0eb9b00-d900-11e8-87a7-42050e5b963d.png)

![image](https://user-images.githubusercontent.com/37112040/47554382-12e51d80-d901-11e8-811c-cc2e0c8e4ee6.png)

**Comment by shankar2105** [comment]
@safesurfer fixed above issue in [PR#90](https://github.com/krishnaIndia/crust_dashboard/pull/90)

We still have issue with the chart on toggling the slider which @ashwinkumar6 is working on it.

**Comment by safesurfer** [comment]
Charts are looks fine and made table horizontally scrollable in mobile view. But when we collapse slider, it disturbs the dropdowns a bit (similar to the issue #1049). @ashwinkumar6 is working on this along with #1049 . So I'm moving this to Done.
