### ISSUE TITLE
Investigate creating an app bundle to resolve error messages

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1056]

**Comment by S-Coyle** [comment]
Issue we will hit here is that when we sign the .app, then the contents change when a log file is created in the package folder structure, then the signature won’t be valid any more.
Potential solutions - lock the .app so that the log file is created in a default system location (app-support)?

**Comment by S-Coyle** [comment]
Created a working .app but decided to release with the unix executable as it worked fine in v1 and we were approaching code freeze without an implemented solution for where the client log file would create
