### ISSUE TITLE
`PeerNotFound` error that comes from Crust - Jim's results

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1060]
Log output that we got:
```
thread 'main' panicked at '
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   unwrap! called on Result::Err                                              !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
examples/client.rs:1263,21 in client
Err(Crust(PeerNotFound))
', /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/unwrap-1.2.1/src/lib.rs:67:25
```

**Comment by S-Coyle** [comment]
No details of what was done, if anything, to resolve this - @nbaksalyar could you update with what was done here?

**Comment by nbaksalyar** [comment]
>could you update with what was done here?
Sure @S-Coyle. We just don't panic in this case: it's a rare occasion when Crust reports that a direct connection was established but while we're trying to get a peer's IP address it's already disconnected at that point in time (hence `PeerNotFound`). Now we just ignore the result and don't report it as a successful connection.

**Comment by S-Coyle** [comment]
Thanks Nikita, closing issue.
