### ISSUE TITLE
List of countries in filter is only updated after full browser refresh

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/crust#1068]

**Comment by bochaco** [comment]
You are probably right @safesurfer , when I saw this I haven't realised of the refresh button, I thought it was like the crust-tet-v1 dashboard and was expecting it to refresh automatically, so I went to refresh the page directly.

**Comment by S-Coyle** [comment]
Looks like this was just a misunderstanding rather than an issue - no reports of it since v2 release so closing
