### ISSUE TITLE
Byteorder version is conflicting

### ISSUE THREAD

**Issue by Bombfuse** [maidsafe/crust#1071]
I'm using another library that uses byteorder, and it seems that Crust uses an older version which is causing conflict issues. The library uses 1.2.1 and above, while Crust uses 1.1.0 only. Are there any simple solutions here?

**Comment by povilasb** [comment]
We updated all the dependencies with this PR: https://github.com/maidsafe/crust/pull/1094/files . See if that helps :)

**Comment by povilasb** [comment]
Actually, Crust is not using byteorder anymore. So closing the issue.
