### ISSUE TITLE
NewConnection events should not include bootstrapped endpoint

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/crust#109]
Bootstrap method is blocking and returns endpoint it bootstrapped with. Crust also fires a new connection event even for bootstrapped endpoint. We need not to have both options here.

This is happening due to generic handling of all connection including bootstrap connections.
One potential fix will be:  For bootstrap connection, only add connection to the state object if it is selected and returned as bootstrap endpoint. Also don't fire new connection event.

This will become major issue once we start doing parallel bootstrapping (Mike's PR #108). 
As even after bootstrap method returns, crust will continue its parallel bootstrapping and new connection event will be fired along with keeping all tried connection in state object.

**Comment by dirvine** [comment]
Can we identify specifically a bootstrap event? Then it is up to users to decide what to do with these, so they can get up to X (15) with each call to bootstrap?

**Comment by chandraprakash** [comment]
Not currently. All new connections including bootstrapped connection are reported via NewConnection event.

**Comment by dirvine** [comment]
Could we progress this in crust for next version perhaps?

**Comment by chandraprakash** [comment]
Ok,  I will create a JIRA task related to this issue and update TODO for the next version.

**Comment by chandraprakash** [comment]
Jira task for this issue https://maidsafe.atlassian.net/browse/MAID-1136
