### ISSUE TITLE
Possibility of multiple localhost address during bootstrap

### ISSUE THREAD

**Issue by ustulation** [maidsafe/crust#1090]
Since ServDisc returns loopback address too if a listener is bound to it, multiple machines in a LAN might respond to a seeking/beaconing peer and they might all have loopbacks in their response. So in [places like these](https://github.com/maidsafe/crust/blob/bafde11bd33474ca3cfe2357d9b2d41364cdb831/src/main/bootstrap/mod.rs#L238) one might end up with multiple loopback addresses and try all of them (where at-most one will succeed if at all) which is wasteful. Either filter to remove duplicates there or turn [this vec](https://github.com/maidsafe/crust/blob/bafde11bd33474ca3cfe2357d9b2d41364cdb831/src/main/bootstrap/mod.rs#L42) into a `HashSet`.

As usual, analyse this does not break anything else.

**Comment by 1uka** [comment]
Taking this up, as it seems like a good first issue to get acquainted with the code.
