### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by 3bdallahz** [maidsafe/crust#1121]
I'm trying to run the example in `examples/crust_peer.rs` and I'm not being able to run it.
here is what I did:

![peek 2019-02-04 19-54](https://user-images.githubusercontent.com/46962022/52226935-ebfe9600-28b6-11e9-99b8-131c7a71c009.gif)

**Comment by povilasb** [comment]
Thanks for the feedback! I believe PR https://github.com/maidsafe/crust/pull/1123 should fix the issue. Also, see the comments for explanation :)

**Comment by douglascaetano** [comment]
Hi @3bdallahz!

Thanks for your report. There was indeed an issue, as mentioned by @povilasb, that we fixed in PR #1141. Please pull the changes and try again. If the problem persists, please reopen this issue.
