### ISSUE TITLE
Remove message priorities

### ISSUE THREAD

**Issue by povilasb** [maidsafe/crust#1133]
ETD + review: 2 days

Currently Crust has messages with different priorities. This implies more complexity. Routing does not use those priorities hence we decided to remove them until other Crust users express desire this functionality.

Priorities will have to be removed from 2 crates:

1. crust: message send API
2. socket-collection: see the [out_queue.rs](https://github.com/maidsafe/socket-collection/blob/b2c235fb820312661137151131bdcb4560b75bfa/src/out_queue.rs)

**Comment by ustulation** [comment]
This will be post-fleming so closing for now
