### ISSUE TITLE
Report about dropped messages

### ISSUE THREAD

**Issue by povilasb** [maidsafe/crust#1134]
ETD + review: 2.5 days

## The problem

1. crust `Service::send()` will buffer given message.
2. If message is not flushed withing 60 seconds, it is silently dropped.

## Solution

1. Change message expire time to 120 seconds.
2. The actual buffering implementation is in socket-collection and it actually drops a whole queue rather than just one message. Message TX queue has many queues internally: one queue per priority. If first message of specific queue is expired, it will drop the whole queue. Make sure we only drop a single message instead. See: https://github.com/maidsafe/socket-collection/blob/master/src/out_queue.rs#L41
3. Report/emit event about the dropped message to crust users.

## Alternatives

We've been thinking of FIFO message queue with back pressure and message serialization to disk on shutdown. Hence, the whole dropped message notification procedure would be redundant. Maybe we should implement FIFO message queue right away?

**Comment by ustulation** [comment]
>  Message TX queue has many queues internally:

Based on [this](https://github.com/maidsafe/pre-rfc/pull/18#discussion_r257658899) there would be just one queue moving f/w (as Crust is not supposed to deal with priorities any more). This size should be settable by the upper layer lib and back-pressure reported once it's full ?

**Comment by douglascaetano** [comment]
Closing this one as we decided the other way around, i.e., we will not notify message dropping anymore. See #1150 and other issues related to dynamic connections for more information.
