### ISSUE TITLE
Solve head of line blocking

### ISSUE THREAD

**Issue by povilasb** [maidsafe/crust#1135]
## The Problem

Currently the maximum message size Crust allows to send is 2 MB. The limit is there for a reason: we don't want upper layers to put too big TCP packets on the stream because it would simply clog the line. Basically this is [head-of-line blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking) problem. Crust users might and should not be aware of it - we strive for simplicity.

Design the changes so that `Service::send(msg_100mb)` would not delay `Service::send(msg_10kb)` delivery for too long.

## Solution

1. Crust should fragment the data it's given before sending over TCP.
2. Then on the other side packets should be defragmented, buffered and proper crust events dispatched when a full packet arrives.
3. See if this multiplexer library could help: https://github.com/paritytech/yamux

**Comment by douglascaetano** [comment]
Closed in favor of #1145.
