### ISSUE TITLE
Connection attempt fails

### ISSUE THREAD

**Issue by pharazen** [maidsafe/crust#1144]
After the latest commit I am able to successfully connect to myself on localhost. However when attempting to connect with another user we both simply get:
```
Received event ConnectFailure(PeerId {.........key data here........}) (not handled)
```
Is there some way to debug further? The only thing I know is it's a connect failure. I guess it's timing out?

**Comment by pharazen** [comment]
Let me be clear that we did follow (i think) the expected process:

1) User A and B both call `prepare-connection-info` and exchange the key
2) User A enters `connect 0 {User B data}
3) User B enters `connect 0 {User A data}

Then nothing happens for about 10 seconds, and it gives ConnectFailure (not handled)

**Comment by pharazen** [comment]
Still unable to debug this, any ideas?

**Comment by S-Coyle** [comment]
Hi @pharazen I'm just testing this now so I'll get back to you with my findings

**Comment by S-Coyle** [comment]
Progress update on where I've got to with this...
- I was able to connect two peers from different networks to each other by manually opening the relevant ports on the routers that the peers were listening on. Note that I also had to edit the "for_direct" section of the connection info before pasting it into the other peer, as I only had internal IPs, so I added the external IP and port number. Connection successful.
- If UPnP is enabled on the 2 peer's routers then as far as I understand, you should be able to connect without port forwarding, as this should take care of it for you, but UPnP does not work on the 2 routers I have access to. I'm hoping to rope a couple of others who have routers with working UPnP into helping me verify this tomorrow. Will update this issue accordingly.

Note that I'm assuming you are behind a NAT, as I am.

**Comment by S-Coyle** [comment]
Update - apologies, I've had no bandwidth to get back to this as yet due to other work taking priority.

**Comment by S-Coyle** [comment]
Repository no longer under active development, replaced by https://github.com/maidsafe/quic-p2p
