### ISSUE TITLE
Random Endpoint generation for tests

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/crust#120]
There is no 'tool' for generating a random endpoint for tests.  Possiblty worth considering.

**Comment by zacstewart** [comment]
Could you clarify this a little? I'm still trying to get a grip on the terminology: what is an endpoint in this context?

In the Ruby world, there are tools like Faker and Forgery which can generate random pieces of data like phone numbers and IP addresses. Are you looking for something like that here?

**Comment by chandraprakash** [comment]
Enpoint is an Enum representing endpoint of supported protocols in crust. 
https://github.com/maidsafe/crust/blob/master/src/transport.rs#L32

You can see an example here: https://github.com/maidsafe/routing/blob/master/src/test_utils/types_util.rs

**Comment by dirvine** [comment]
If you check the utp repo you will find how they use this very similar feature :-) https://github.com/meqif/rust-utp/blob/master/tests/stream.rs

**Comment by chandraprakash** [comment]
There is an implementation already in routing and you need to update it crust.(using Random trait) 
https://github.com/maidsafe/routing/blob/master/src/test_utils/messages_util.rs#L28

**Comment by inetic** [comment]
@benjaminbollen @dirvine, so Routing currently has its own function to generate random Endpoints and Connections, could you confirm that this is OK and we can close this issue or whether you want Crust to export such functionality.

**Comment by inetic** [comment]
I may have accidentally opened this issue myself :-P, closing again.
