### ISSUE TITLE
Documentation not explicit enough

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#129]
Ben had issues when trying to use Crust despite having read the docs (http://maidsafe.net/crust/crust/connection_manager/struct.ConnectionManager.html).

As well as cleaning up and checking that the existing comments are valid, it would be good to perhaps be a bit more explicit about when events are fired, particularly with regards to bootstrapping and the `NewConnection` and `LostConnection` events.

**Comment by dirvine** [comment]
This was updated by PRakash, so will close for now.
