### ISSUE TITLE
First node doesn't read its own bootstrap list

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#134]
When running the crust_peer example, if the node is the first on the LAN (i.e. it manages to start listening on the beacon port and doesn't connect to any other nodes via the beaconing method) then it disregards its own bootstrap list.

**Comment by chandraprakash** [comment]
I have applied the fix and now the file is read, but it now exposes that there is a logic missing to avoid bootstrapping off self. On testing, I could find that the node is bootstrapping off self. 
Working on updating that logic as well to have it working.
