### ISSUE TITLE
Bootstrap file format

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#140]
The bootstrap file's contents are all contained on one line.

It would be good to do some sort of "pretty print" to make it easier to read and modify this file.

**Comment by Fraser999** [comment]
@vinipsmaker Sorry - I didn't know this had been assigned to you when I started the task :-(

**Comment by chandraprakash** [comment]
@Fraser999 You can check https://waffle.io/maidsafe/crust to see who is on which task.
Thanks for the fix.
