### ISSUE TITLE
"stop" fails on Linux

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#141]
The stop command in the crust_peer example in Linux seems to no longer work.

**Comment by southsideGLA** [comment]
If I run multiple instances of 
cargo run --example crust_peer
then the stop command works fine on all but the last remaining instance.
If I only run a single instance then it also fails and I require a ctrl-c to regain the prompt.
Latest git versions of all libs and last nights rust on Ubuntu 15.04

**Comment by chandraprakash** [comment]
This might be related to shut-down of the beacon server. I have not yet looked into the code.
Its only the first node which acquires the beacon port (on a machine). I will update after investigating it.

**Comment by vinipsmaker** [comment]
The code blocks on [beacon.rs:L172](https://github.com/maidsafe/crust/blob/ca7a18812826775773da64fe5fed733fd4dba406/src/beacon.rs#L172)/`std::net::addr::SocketAddr::recv_from`.

I'm studying [the commit that introduced such feature](https://github.com/Fraser999/crust/commit/99e34b8902a43e6dd920a7ef4f9c23fc0ca8e295) to fix the issue.

**Comment by vinipsmaker** [comment]
`std::net::addr::SocketAddr::recv_from` is used to wait for the other thread to finish cleanly. The problem is that the `crust_peer` example calls `ConnectionManager::stop` twice and `BroadcastAcceptor::stop` doesn't handle "double stop correctly". I'll write a patch soon.
