### ISSUE TITLE
Target musl on linux 

### ISSUE THREAD

**Issue by dirvine** [maidsafe/crust#172]
Rust 1.1 now targets musl, this will means 100% statically linked binaries with zero dependencies

**Comment by vinipsmaker** [comment]
And rather small binaries, possibly.

![1433438646882](https://cloud.githubusercontent.com/assets/865914/8379537/0e67e74e-1bf7-11e5-9f57-39f8606312e8.png)

**Comment by dirvine** [comment]
Very nice :-) I really like statically linked binaries actually. This is very neat indeed. Wish we had same for  osx (possible perhaps) and windows (ha I wish). Although Windows perhaps is not so bad, but we will see. At least for non gui this is great.
