### ISSUE TITLE
Bootstrap protocol fails

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#173]
Running an example from the MaidSafe Client project shows that a client can't connect to a vault network which is running on remote Droplets.

The example doesn't allow for passing through endpoints via the command line (as other examples do) which means that I added six endpoints to the bootstrap file before launching the example.

I tried adding the list of endpoints to the hardcoded section and the contacts section of the file.

The client apparently doesn't connect to any of the running vaults.

**Comment by dirvine** [comment]
The task here is to get it to work with the bootstrap file first. IF we want examples to take endpoints they will need to read & write that file.

**Comment by Fraser999** [comment]
Further info: #174 was filed at the same time as this issue.  From the bootstrap file after running the example, I can see that it has added only its own details - the client was running on 192.168.1.65 and there were no other MaidSafe executables running on that same machine at the same time.

**Comment by chandraprakash** [comment]
Did you try with the bootstrap file with the correct format? (as mentioned in #174 )

**Comment by Fraser999** [comment]
Yes - operator error to blame :-)

**Comment by chandraprakash** [comment]
Cheers Fraser !
