### ISSUE TITLE
Create crust_irc client

### ISSUE THREAD

**Issue by a-jamesregan** [maidsafe/crust#182]
I would like to create a crust_irc client based off of the crust_peer example, but I don't know enough rust to create it.  I gave it my best shot, but diving right into a project like this with 0 rust experience is just over my head!  So, I decided to try the next best thing: creating the design specifications!

https://github.com/a-jamesregan/crust/blob/crust-irc/docs/crust_irc.md

The crust_peer example works well enough as an irc client, but it has a few annoyances that need fixed for it to be usable.  The biggest one is the ability to type "send nick message" instead of "send 192.168.1.23:5640 message_goes_here" and receiving messages in an irc-like format.

**Comment by southsideGLA** [comment]
+1
Now off to read the crust book again and look at the code for other IRC clients

**Comment by dirvine** [comment]
:+1:  Great to see, Hopefully we will get some apace to help you out here. @vinipsmaker  and @chandraprakash  may be able to take a peek and keep you on track. Fantastic !!

**Comment by vinipsmaker** [comment]
If you come from a C++ and Haskell background, Rust will be really fast to pick up. And the Rust community is very inviting. The lifetime thing is the only feature that is Rust-exclusive.

Also, Rust makes it easy to export functions as C libraries. So, this isn't all-or-nothing.

Let us know if you have any troubles. We might improve documentation a lot depending on feedback.

**Comment by a-jamesregan** [comment]
Great!  I'm stumbling through the basics of rust, but I right now I'm kind of stumped.  Is there a developer chat I can go to in order to get help with this?

**Comment by vinipsmaker** [comment]
> Is there a developer chat I can go to in order to get help with this?

I run to the [Freenode's `#rust`](https://kiwiirc.com/client/chat.freenode.net/#rust) channel when I'm in trouble and the guys there are very receptive.

I'd also suggest the [`rust` subreddit](https://www.reddit.com/r/rust/).

**Comment by southsideGLA** [comment]
#rust appears to be invite only...  Any chance you could send an invite to freenode user *southside* please?

**Comment by vinipsmaker** [comment]
> #rust appears to be invite only... Any chance you could send an invite to freenode user southside please?

Sorry, the actual channel is [`##rust`](https://kiwiirc.com/client/chat.freenode.net/##rust).

**Comment by southsideGLA** [comment]
Ah OK  thanks :-)

**Comment by inetic** [comment]
@a-jamesregan, I'm going to close this issue as there has not been any activity for some time. If you need help with Crust, feel free reopening this issue or creating a new one and we'll try our best.
