### ISSUE TITLE
trapped msg communication during connection establishment

### ISSUE THREAD

**Issue by maqi** [maidsafe/crust#189]
When I am looking at the failed vault::executable_test issue in OSX, a strange behaviour is noticed:
for some reason, a node's msg connection will be trapped in receiving un-recognized msg infinitely.
i.e. It is observed that for a potential peer connection, `Ok(crust::Event::NewMessage(endpoint, bytes)) =>` in routing will be constantly called and the incoming msg from the same endpoint turns out to be unrecognizable.
and once one side falls into this state, it can't recover from it, and can not put peer node into its routing table. (even the peer has already succeeded in doing so)

Although it is on routing level this behaviour is observed, because it is crust making such event call, so I am raising this issue in crust lib first.
If it turns out to be some bug in routing, please move the issue to routing, thanks.

**Comment by vinipsmaker** [comment]
Is this issue still happening? Can you give instructions to reproduce the issue if so?

**Comment by brian-js** [comment]
The issue has been resolved, closing.
