### ISSUE TITLE
Bootstrap file location

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#193]
The bootstrap file is located in the current working dir (at the time when the app is started).

This makes it pointless to install a default bootstrap file, since it will be ignored unless the user happens to cd to the location of the installed file before starting the app.

**Comment by dirvine** [comment]
This is exactly what we want to see from the installer tasks. So this is basically a very simple issue that requires some thought. We have options here of where this is located and what it is called and what permissions it should have. All of these require answers that are not available just looking at code. I suggest a discussion here that addresses these issues. Something like 


1. Location
Options (per OS) - Pro's Cons 

2. Name
Options (per OS) Pro's Cons

3. Permissions 
Options (per OS) Pro's Cons

OS == Windows, Linux, OSX plus BSD Android IOS

When these are answered then we know what to use. This discussion should be facilitated by Qa and progressed via any tasks required to be done in the code. The purpose is to look at what we provide from the *users* perspective. The *users* in this case being *App developers* and *end users* so it is not about what we personally prefer in any way, this is all about satisfying an audience.

**Comment by chandraprakash** [comment]
Default config file/cache file path needs to be current_exe_path.
This also need to be documented in sync with installer.

**Comment by Fraser999** [comment]
Fixed in https://github.com/maidsafe/crust/pull/268.
