### ISSUE TITLE
TCP simultaneous connect while looping to bootstrap to a list of endpoints

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/crust#195]
Due to looping to connect to cached contacts, two client trying to connect to same local port (not listening & unoccupied) connect to each other. (TCP simultaneous connect)

Steps to reproduce:

##### 1. Start first crust peer and close it once it starts listening.

    prakash@machine:~/rust/maidsafe/crust (MAID-1136_new_bootstrap_event)$ cargo run --example crust_peer
       Compiling crust v0.1.5 (file:///home/prakash/rust/maidsafe/crust)
         Running `target/debug/examples/crust_peer`
    Error reading Bootstrap file: Error { repr: Os { code: 2, message: "No such file or directory" } }. Creating "./crust_peer.bootstrap.cache".
    Listening for new connections on Tcp(V4(127.0.0.1:45574)), Tcp(V4(192.168.0.10:45574)), Tcp(V6([::1]:45574)), Didn't bootstrap to an existing network - this may be the first node of a new network.
    ^C

Bootstrap cache will have listening endpoints added (currently unused)

    prakash@machine:~/rust/maidsafe/crust (MAID-1136_new_bootstrap_event)$ cat crust_peer.bootstrap.cache 
    [
      {
        "endpoint": "127.0.0.1:45574"
      },
      {
        "endpoint": "192.168.0.10:45574"
      },
      {
        "endpoint": "[::1]:45574"
      }
    ]prakash@machine:~/rust/maidsafe/crust (MAID-1136_new_bootstrap_event)$

##### 2. Start first crust peer again and it can be noticed that it bootstrapped with its previous listening port.

>     prakash@machine:~/rust/maidsafe/crust (MAID-1136_new_bootstrap_event)$ cargo run --example crust_peer
>          Running `target/debug/examples/crust_peer`
>     Listening for new connections on Tcp(V4(127.0.0.1:37180)), Tcp(V4(192.168.0.10:37180)), Tcp(V6([::1]:37180)), 
>     New BootstrapConnection to peer at Tcp(V4(192.168.0.10:45574))
>     1 connected node: Tcp(V4(192.168.0.10:45574))
>     Enter command (stop | connect <endpoint> | send <endpoint> <message>)>Bootstrapped to Tcp(V4(192.168.0.10:45574))
>     Got at least one bootstrap connection. Breaking bootstrap loop.
>     
>     Enter command (stop | connect <endpoint> | send <endpoint> <message>)>

lsof output

     prakash@machine:~$ lsof  -i :45574
    COMMAND     PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
    crust_pee 16100 prakash   11u  IPv4 1603649      0t0  TCP 192.168.0.10:45574->192.168.0.10:45574 (ESTABLISHED)
    crust_pee 16100 prakash   13u  IPv4 1603649      0t0  TCP 192.168.0.10:45574->192.168.0.10:45574 (ESTABLISHED)

**Comment by vinipsmaker** [comment]
[I coded a solution](https://github.com/vinipsmaker/crust/tree/fix195) after reading about the tradeoffs from the several solutions. This solution is portable and works now.

@chandraprakash did most of the research when I started to work on the task, so it was easy & fast to pick up where he left.
