### ISSUE TITLE
Allow to specify configuration from API instead of a file

### ISSUE THREAD

**Issue by kryptan** [maidsafe/crust#208]
Having one config file in a hardcoded location may be fine for your use-case but if this library is supposed to be usefull for other server-less / decentralised projects then there should be a way to specify all neceasarry information using API. One obvious use-case that doesn't work well with one config file per process is connecting to multiple decentralized network (currently the only way I see to do it is to change currrent directory before creating ConnectionManager, correct me if I'm wrong).

**Comment by dirvine** [comment]
This file tho is per application not per crust process. So if you have an app called app. There will be an app.crust.config file. IF no system wide config is found then it will be in your home dir settings. If you wanted several config files per user then you can have this on a per directory basis. The config file though should only be storing app issues like seed nodes and not any per application specific parts. This means that you are not having to pass files configs through several layers of libraries etc. 

We are testing this now and need to document it very clearly though. It maybe we can supply an additional API where folk can pass the same file path down through all of their libraries and override this behaviour. For us in our cases we do not want to pass info through libraries unless we need to (like app specific items like accept_on ports or hard coded endpoints, these are specific per application instance (or can be)

**Comment by madadam** [comment]
I believe this can be closed: https://github.com/maidsafe/crust/blob/master/src/service.rs#L146
