### ISSUE TITLE
No mechanism to prevent nodes from different decentralized networks to connect to each other

### ISSUE THREAD

**Issue by kryptan** [maidsafe/crust#209]
I haven't yet explored source code in detais, but it seems that there is no such mechanism (at least I didn't find any). Imagine that people will start to use this library to create all sorts of decentralized things. Nodes from different swarms will connect to each other. You don't want your Bitcoin client to connect to BitTorrent swarms or different BitTorrent swarms to connect to each other. Of course this will be detected at higher level protocol but I think that Crust should detect it by itself. 

I suggest that there should be some id passed to ConnectionManager which will be send to other nodes and each node will check that this id is what it wants. This id should be large enough to prevent collisions.

**Comment by dirvine** [comment]
This is where the connect to previous known nodes works, these should all be your previous version of the network you were connected to. Your networks should not cross pollinate in any way, at least they cannot as different networks. So this should actually be OK. If no nodes are found then you can have hard coded endpoints (in the config file) to bootstrap your bootstrap cache file and then only add nodes you successfully connect to (so should be your network). 

Hope that makes sense. Perhaps the docs need updated to make this very clear, I will leave this open and label docs required.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
