### ISSUE TITLE
Need drop_and_forget() API to remove cached entry of a bad node

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/crust#220]
if any upper layer detects a bootstrap node / node is misbehaving or a security concern it would be good if we can kill it from our bootstrap list and not have to go through all the checks again to find he is a bad node.

`drop_and_forget()` can explicitly mean do not cache it and remove from cache if present in cache.
There are situations when we only want to drop a connection but still cache it in bootstrap list, but other times it may be a very bad node we don't want to speak to again.

**Comment by vinipsmaker** [comment]
Fixed by https://github.com/maidsafe/crust/pull/459
