### ISSUE TITLE
test failures on Linux

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/crust#222]
I've been seeing these for a while (doing regular builds and tests of everything using nightly Rust) and reporting them in case. Is this expected, or due to my not having something set up here?

====== crust ======
   Compiling crust v0.2.1 (file:///home/mrh/src/maidsafe-rust/crust)
     Running target/debug/crust-2085f7d00e4c5041

running 18 tests
test bootstrap_handler::test::serialisation ... ok
test config_utils::test::read_config_file_test ... FAILED
test bootstrap_handler::test::duplicates ... FAILED
test bootstrap_handler::test::prune ... FAILED
test connection_manager::test::bootstrap_off_list_connects ... ok
test bootstrap_handler::test::oldest ... FAILED
test connection_manager::test::network ... ignored
test getifaddrs::test::test_getifaddrs ... ok
test tcp_connections::test::test_small_stream ... ok
test test::check_rust_unit_testing_is_not_parallel ... FAILED
test transport::test::test_ord ... ok
test beacon::test::test_beacon ... ok
test tcp_connections::test::test_multiple_nodes_small_stream ... ok
test beacon::test::test_avoid_beacon ... ok
test bootstrap_handler::test::max_contacts ... ok
test connection_manager::test::connection_manager ... ok
Got at least one bootstrap connection. Breaking bootstrap loop.
test connection_manager::test::bootstrap ... ok
test connection_manager::test::connection_manager_start ... ok

failures:

---- config_utils::test::read_config_file_test stdout ----
	thread 'config_utils::test::read_config_file_test' panicked at 'assertion failed: `(left == right)` (left: `Some(Config { override_default_bootstrap: false, hard_coded_contacts: [], beacon_port: 0 })`, right: `Some(Config { override_default_bootstrap: false, hard_coded_contacts: [Contact { endpoint: Tcp(V4(50.238.202.128:34947)) }, Contact { endpoint: Tcp(V4(131.24.218.173:37067)) }, Contact { endpoint: Tcp(V4(37.125.137.185:56142)) }, Contact { endpoint: Tcp(V4(230.235.85.254:31930)) }, Contact { endpoint: Tcp(V4(243.231.200.132:40974)) }, Contact { endpoint: Tcp(V4(212.184.27.129:45747)) }, Contact { endpoint: Tcp(V4(156.237.218.148:14295)) }, Contact { endpoint: Tcp(V4(3.136.167.193:49065)) }, Contact { endpoint: Tcp(V4(253.10.203.66:24962)) }, Contact { endpoint: Tcp(V4(200.234.64.216:28361)) }], beacon_port: 17450 })`)', src/config_utils.rs:174

---- bootstrap_handler::test::duplicates stdout ----
	Error reading Bootstrap file: Error { repr: Custom(Custom { kind: Other, error: StringError("Error decoding bootstrap file: ParseError(SyntaxError(\"EOF While parsing value\", 1, 1))") }) }. Creating "/home/mrh/src/maidsafe-rust/crust/target/debug/crust-2085f7d00e4c5041.crust.bootstrap.cache".
thread 'bootstrap_handler::test::duplicates' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Error decoding bootstrap file: ParseError(SyntaxError(\"trailing characters\", 33, 4))") }) }', ../src/libcore/result.rs:731

---- bootstrap_handler::test::prune stdout ----
	Error reading Bootstrap file: Error { repr: Custom(Custom { kind: Other, error: StringError("Error decoding bootstrap file: ParseError(SyntaxError(\"EOF While parsing value\", 1, 1))") }) }. Creating "/home/mrh/src/maidsafe-rust/crust/target/debug/crust-2085f7d00e4c5041.crust.bootstrap.cache".
thread 'bootstrap_handler::test::prune' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Error decoding bootstrap file: ParseError(SyntaxError(\"EOF While parsing value\", 1, 1))") }) }', ../src/libcore/result.rs:731

---- bootstrap_handler::test::oldest stdout ----
	Error reading Bootstrap file: Error { repr: Custom(Custom { kind: Other, error: StringError("Error decoding bootstrap file: ParseError(SyntaxError(\"EOF While parsing value\", 1, 1))") }) }. Creating "/home/mrh/src/maidsafe-rust/crust/target/debug/crust-2085f7d00e4c5041.crust.bootstrap.cache".
Error reading Bootstrap file: Error { repr: Custom(Custom { kind: Other, error: StringError("Error decoding bootstrap file: ParseError(SyntaxError(\"EOF While parsing value\", 1, 1))") }) }. Creating "/home/mrh/src/maidsafe-rust/crust/target/debug/crust-2085f7d00e4c5041.crust.bootstrap.cache".
thread 'bootstrap_handler::test::oldest' panicked at 'assertion failed: `(left == right)` (left: `[]`, right: `[Contact { endpoint: Tcp(V4(147.97.142.162:52049)) }, Contact { endpoint: Tcp(V4(240.94.14.137:47233)) }, Contact { endpoint: Tcp(V4(251.102.94.24:26912)) }, Contact { endpoint: Tcp(V4(81.229.169.199:57497)) }, Contact { endpoint: Tcp(V4(214.74.113.130:26831)) }, Contact { endpoint: Tcp(V4(48.89.38.140:49535)) }, Contact { endpoint: Tcp(V4(98.221.163.132:61498)) }, Contact { endpoint: Tcp(V4(192.180.121.248:692)) }, Contact { endpoint: Tcp(V4(188.23.25.126:15078)) }, Contact { endpoint: Tcp(V4(170.50.212.87:59641)) }, Contact { endpoint: Tcp(V4(69.191.25.173:64164)) }, Contact { endpoint: Tcp(V4(237.233.179.242:57953)) }]`)', src/bootstrap_handler.rs:390

---- test::check_rust_unit_testing_is_not_parallel stdout ----
	thread 'test::check_rust_unit_testing_is_not_parallel' panicked at 'RUST_TEST_THREADS needs to be 1 for the crust unit tests to work', src/lib.rs:54

failures:
    bootstrap_handler::test::duplicates
    bootstrap_handler::test::oldest
    bootstrap_handler::test::prune
    config_utils::test::read_config_file_test
    test::check_rust_unit_testing_is_not_parallel

test result: FAILED. 12 passed; 5 failed; 1 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', ../src/libtest/lib.rs:254

**Comment by chandraprakash** [comment]
Thanks for reporting the issue. 
Currently crust tests don't support parallel run.
As rust runs tests in parallel by default, we need to set the variable:  `RUST_TEST_THREADS`.

Set this variable and you should be okay.
`export RUST_TEST_THREADS=1`
