### ISSUE TITLE
Request: can Crust provide a get_all_endpoints ?

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/crust#225]
Only on the condition this does not introduce additional state for CRUST,
is it possible to expose a `get_all_endpoints() -> Vec < Endpoint >`; - it does not need to differentiate between whether those are bootstrap connections to us or 'normal'

routing does store and follows up every new connection, but it would open the option to trim possible unneeded connections; open to discussions

**Comment by vinipsmaker** [comment]
Crust is moving more and more to asynchronous approach. Not sure if it seems right to add this function. Even if this function is added, user will still need to handle `OnConnect`/`OnAccept` and `LostConnection` to be aware when changes to the list returned by `get_alld_endpoints()` happens (and this approach is possibly racy too).

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
