### ISSUE TITLE
Find stable solution to Error: use of unstable library feature 'udp_extras'

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/crust#226]
See the following for details of finding a more permanent / stable solution, assigning to @mmoadeli 

https://github.com/maidsafe/crust/issues/223
https://github.com/maidsafe/crust/pull/224#issuecomment-126651635

**Comment by vinipsmaker** [comment]
Wasn't this issue solved in b83d29b9653ece9e134797570e945a88d9767aa6 ?

**Comment by dirvine** [comment]
Partly resolved with that commit, but still using unstable features. I suspect the switch to channels and rid ourselves of weak references will allow us complete stability.

**Comment by vinipsmaker** [comment]
> but still using unstable features

Should I change the name of the issue to reflect that it should track the use of all unstable features?

**Comment by dirvine** [comment]
Or perhaps close this and have an issue for each feature? then we can knock them off one at a time.

**Comment by vinipsmaker** [comment]
Well, the way I see, this is a duplicate of #235. Closing.
