### ISSUE TITLE
OS X - test tcp_connections::test::test_multiple_nodes_small_stream ... FAILED

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/crust#228]
Travis OS X - test tcp_connections::test::test_multiple_nodes_small_stream ... FAILED
```
$ rustc --version

rustc 1.3.0-nightly (4dfe7a16c 2015-07-30)

$ cargo --version

cargo 0.4.0-nightly (e0a82d6 2015-07-29) (built 2015-07-30)
```

For example > https://travis-ci.org/maidsafe/crust/jobs/73546406

```
test tcp_connections::test::test_multiple_nodes_small_stream ... FAILED

test tcp_connections::test::test_small_stream ... ok

test test::check_rust_unit_testing_is_not_parallel ... ok

test transport::test::test_ord ... ok

failures:

---- tcp_connections::test::test_multiple_nodes_small_stream stdout ----

	thread 'tcp_connections::test::test_multiple_nodes_small_stream' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', ../src/libcore/result.rs:732

failures:

    tcp_connections::test::test_multiple_nodes_small_stream

test result: FAILED. 16 passed; 1 failed; 1 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', ../src/libtest/lib.rs:253
```

**Comment by vinipsmaker** [comment]
@rossmuir: we open many file descriptors in tests to increase the chance to detect some race (Rust can detect data races in compile time, but there are other kind of concurrency problems). Just increase the OS X limits for open file descriptors:

    ulimit -n 1024

**Comment by rossmuir** [comment]
Thanks @vinipsmaker but I would rather find a fix that does not alter system-wide settings

**Comment by dirvine** [comment]
What about, 

If we are on osx we reduce the number of connections. As many folk will download and do cargo run, cargo test etc. then this is an issue. 

However we add a CI ENV_VAR called CI or similar (I am sure there is one) where on the CI script we do increase this count and set the var, in the test check for this var and osx and if set run the increased connections.

**Comment by vinipsmaker** [comment]
I'm not sure who (and how) fixed the issue, but seems fine in the latest code.

Should I close the issue?

**Comment by dirvine** [comment]
Yes I think this is OK now.

On Fri, Aug 28, 2015 at 11:16 PM, Vinícius dos Santos Oliveira <
notifications@github.com> wrote:

> I'm not sure who (and how) fixed the issue, but seems fine in the latest
> code.
>
> Should I close the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maidsafe/crust/issues/228#issuecomment-135900217>.
>



-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me
