### ISSUE TITLE
Compile error: Can't build benchmark tests

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#236]
Running `cargo bench` yields the following error:

>     Compiling crust v0.2.3 (file:///I:/MaidSafe/Rust/SuperProject/Crust)
    benches\connection_manager.rs:46:14: 46:68 error: no method named `start_listening` found for type `crust::connection_manager::ConnectionManager` in the current scope
    benches\connection_manager.rs:46     match cm.start_listening(vec![Port::Tcp(cm_listen_port)], None) {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    benches\connection_manager.rs:48:16: 48:24 error: the type of this value must be known in this context
    benches\connection_manager.rs:48             if result.0.len() > 0 {
                                                    ^~~~~~~~
    benches\connection_manager.rs:67:16: 67:75 error: no method named `start_listening` found for type `crust::connection_manager::ConnectionManager` in the current scope
    benches\connection_manager.rs:67   match cm_aux.start_listening(vec![Port::Tcp(cm_listen_port - 10)], None) {
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    benches\connection_manager.rs:69:12: 69:20 error: the type of this value must be known in this context
    benches\connection_manager.rs:69         if result.0.len() > 0 {
                                                ^~~~~~~~
    error: aborting due to 4 previous errors
    Could not compile `crust`.

**Comment by dcampbell24** [comment]
It looks like the benches have not been updated to match changes that happened in the library. I am taking a look at fixing this.

**Comment by dcampbell24** [comment]
Should this bench be based on the connection_manager_start function in src/connection_manager.rs?

**Comment by inetic** [comment]
HI @dcampbell24, sorry for not responding sooner. I only recently had a look at why the test was failing to compile, there have been few API changes that caused this. On top of that, the ConnectionManagers must be started without any network activity (specially beacon discovery) for which we haven't yet had API in crust. Hopefully it is fixed now (works for me locally).

**Comment by vinipsmaker** [comment]
Fixed in #305

**Comment by dcampbell24** [comment]
@inetic no worries. Thanks for providing some insight into what happened and fixing it.
