### ISSUE TITLE
Wire protocol is neither versioned nor tagged for wireshark pattern matching

### ISSUE THREAD

**Issue by ned14** [maidsafe/crust#24]
Can I suggest that crust's wire protocol always begins with this magic:

0x31757263 ("cru1")

This allows future wire protocol upgrade ("cru2") plus lets wireshark spot the protocol.

**Comment by dirvine** [comment]
Is it a security leak tho and perhaps something we should consider switches
off in release ? I like the magic though and it makes sense.

On Mon, Apr 20, 2015 at 6:02 PM, Niall Douglas <notifications@github.com>
wrote:

> Can I suggest that crust's wire protocol always begins with this magic:
>
> 0x31757263 ("cru1")
>
> This allows future wire protocol upgrade ("cru2") plus lets wireshark spot
> the protocol.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dirvine/crust/issues/24>.
>



-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by ned14** [comment]
You'll need some sort of versioning in there whatever happens, else you have one of hell of a problem later on. So how about this:

0x63 0x72 0x75 0x31: this packet is v1 and unencrypted
0x01 L1 L2 L3: this packet is v1 and encrypted and L1..L3 is the payload length/offset to next encrypted packet.

**Comment by dirvine** [comment]
Let me think on it a bit. I think tor ha same idea and issue ? https://wiki.wireshark.org/Tor

**Comment by ned14** [comment]
If you're doing TLS over UDP (DTLS), then inside the decrypted UDP packet you still need to version. One could look at crust currently as being merely not TLSed, and otherwise identical post-decrypt.

I'd get DTLS into crust sooner rather than later though, if you're choosing that. It has non-obvious consequences.

**Comment by ned14** [comment]
Hmm DTLS has a vulnerability ... http://www.isg.rhul.ac.uk/~kp/dtls.pdf

**Comment by dirvine** [comment]
Yes I spoke to one of the authors a while back. In general though my thoughts are like yours, have a magic and implement full encryption later will mask the magic. 
I think skype/tor etc. did this really. We can use something slightly better than dtls or tls I think, but in essence adding encryption in a switch able fashion may allow small scale tests at least.
