### ISSUE TITLE
Peer gets many NewConnections , seemly not connected to another peer

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/crust#248]
this relates to, or is very similar to the routing issue raised https://github.com/maidsafe/routing/issues/535

It seems that the second (not the first), third, ... peer can occasionally get a flood of new connections on a very regular interval (every 0,5 ~ 1 sec), and they directly disconnect afterwards.

This seems to stop after more nodes join the network.

I'll post routing example output as soon as it re-occurs

@rossmuir also observed similar behaviour in the routing example?

**Comment by rossmuir** [comment]
@benjaminbollen I have seen this with the first as well
```
DEBUG:routing::routing_node: New connection on Tcp(V4(104.131.85.153:57683))
DEBUG:routing::routing_node: Saying hello I am Node(f99116..403024) on Tcp(V4(104.131.85.153:57683)), confirming None
DEBUG:routing::routing_node: Lost connection on Tcp(V4(104.131.85.153:57683))
DEBUG:routing::routing_node: New connection on Tcp(V4(104.131.85.153:57689))
DEBUG:routing::routing_node: Saying hello I am Node(f99116..403024) on Tcp(V4(104.131.85.153:57689)), confirming None
DEBUG:routing::routing_node: Lost connection on Tcp(V4(104.131.85.153:57689))
```

In the config file ( https://github.com/maidsafe/crust/blob/chandraprakash-patch-1/installer/sample.config ) setting `override_default_bootstrap` to true - appears to stop this

**Comment by rossmuir** [comment]
Additional observation - if you have `simple_key_value_store.crust.bootstrap.cache` with the endpoints added you cannot replicate this - remove the `simple_key_value_store.crust.bootstrap.cache` file and you can reproduce the behaviour.

**Comment by chandraprakash** [comment]
Looks like a valid crust bug. The first node never comes out of bootstrap loop. Will investigate it further.

**Comment by benjaminbollen** [comment]
This issue is not resolved.  

```DEBUG:routing::routing_node: Saying hello I am Node(f76421..971eb9) on Tcp(V4(192.168.1.136:46621)), confirming None
DEBUG:routing::routing_node: Lost connection on Tcp(V4(192.168.1.136:46621))
DEBUG:routing::routing_node: New connection on Tcp(V4(192.168.1.136:46632))
DEBUG:routing::routing_node: Saying hello I am Node(f76421..971eb9) on Tcp(V4(192.168.1.136:46632)), confirming None
DEBUG:routing::routing_node: Lost connection on Tcp(V4(192.168.1.136:46632))
DEBUG:routing::routing_node: New connection on Tcp(V4(192.168.1.136:46639))
DEBUG:routing::routing_node: Saying hello I am Node(f76421..971eb9) on Tcp(V4(192.168.1.136:46639)), confirming None
DEBUG:routing::routing_node: Lost connection on Tcp(V4(192.168.1.136:46639))
```

**Comment by brian-js** [comment]
The first node started gives out this,

DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
DEBUG:crust::connection_manager: Reached max bootstrap connections : 1; Reseting further bs connections
etc,...
