### ISSUE TITLE
Config file needs to handle multiple protocol

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/crust#249]
The endpoint Encodable/Decodable doesn't handle multiple protocol.
This change can be picked from utp work here : 
https://github.com/maidsafe/crust/pull/191/files#diff-ec7d691b5cafdc631a44bf41efa29e95R71

**Comment by vinipsmaker** [comment]
> This change can be picked from utp work here :
https://github.com/maidsafe/crust/pull/191/files#diff-ec7d691b5cafdc631a44bf41efa29e95R71

Thanks for the hint.

**Comment by vinipsmaker** [comment]
Fixed in https://github.com/maidsafe/crust/commit/cb378763d6c7a7e2fa41e352d182717b7a604055
