### ISSUE TITLE
Define exit codes

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#274]
The `FileHandler` class will cause any dependent binaries to terminate if it can't parse a given file.  We need to choose and document the value to use for the exit codes.

Currently I'm using the following:

| Reason | Exit Code |
|:---|:---:|
| Failed to open for any reason other than non-existence | 1 |
| Failed to read | 2 |
| Failed to decode as JSON | 3 |

**Comment by madadam** [comment]
I believe this can be closed as `ConfigFileHandler` (or any other library we depend on) no longer calls `exit`.
