### ISSUE TITLE
crust_peer fails to stop

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#277]
When running two instances of the crust_peer example on Windows, if I stop the second one via the "stop" CLI command, the TCP connections can be seen to close (in the output of the first peer), but the UTP connections seem to persist indefinitely and the second peer hangs rather than stopping.

**Comment by vinipsmaker** [comment]
Can you check if problem still occurs after the https://github.com/maidsafe/crust/pull/295 merge?

**Comment by Fraser999** [comment]
Yes, this is now fixed.
