### ISSUE TITLE
OSX travis failures

### ISSUE THREAD

**Issue by dirvine** [maidsafe/crust#280]
OSX cannot handle the number of open files and the test for osx require to reduce the number of nodes tested.

**Comment by rossmuir** [comment]
@dirvine I this the same issue https://github.com/maidsafe/crust/issues/276 ? Shall I close my issue?

**Comment by dirvine** [comment]
It's fine I will close mine and add to 276

**Comment by rossmuir** [comment]
Thanks :-)
