### ISSUE TITLE
Documentation of ConnectionManager and Event needs updated

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#292]
Some of the [generated docs for `ConnectionManager`](http://maidsafe.net/crust/master/crust/connection_manager/struct.ConnectionManager.html) are out of date, badly formatted and insufficient to be helpful.

I also feel that the [`Event` docs](http://maidsafe.net/crust/master/crust/connection_manager/enum.Event.html) could be more helpfully documented, specifically with regards to the difference between a new connection and a new bootstrap connection.  If this difference is documented elsewhere, it would be useful to provide a link here.

We should probably also have a markdown file in the [docs folder](https://github.com/maidsafe/crust/tree/master/docs) detailing the user-settable options in the config file, and linking to the [sample config file](https://github.com/maidsafe/crust/blob/master/installer/sample.config).

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
