### ISSUE TITLE
Discover public endpoint using internal messages to the P2P network

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#294]

**Comment by vinipsmaker** [comment]
We can store/exchange this info using the handshake `struct`: https://github.com/maidsafe/crust/blob/03d63b4526cf87667c1d1775377398875072c12a/src/transport.rs#L186

**Comment by inetic** [comment]
Done here:
https://github.com/maidsafe/crust/commit/e3c96ca19be046e9401254c8a20f1bd656d2bc69
