### ISSUE TITLE
'ConnectionManager bootstrap loop' panicked

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#304]
This is moved from https://github.com/maidsafe/safe_vault/issues/224

The issue is the `unwrap` in the `seek_peers` function:

    let transport = transport::connect(transport::Endpoint::Tcp(peer)).unwrap();

currently at https://github.com/maidsafe/crust/blob/master/src/connection_manager.rs#L436-L437

It can be triggered by starting an initial node which acquires the beacon port for accepting broadcasts, then starting a second node on the same subnet which will broadcast to the first node, then killing the first node.  This triggers the termination of the `ConnectionManager bootstrap loop` thread on the second node.

**Comment by rossmuir** [comment]
Thank you @Fraser999

**Comment by vinipsmaker** [comment]
I assume you mean this line: https://github.com/maidsafe/crust/blob/2bcdb53fcc33f50b015f71cd1ec8bd9c0c4e4375/src/connection_manager.rs#L452-L453

**Comment by Fraser999** [comment]
Yeah - it is now these lines.

**Comment by inetic** [comment]
https://github.com/maidsafe/crust/blob/23bea70d8f06c9183c556fb83008a0e045039374/src/state.rs#L273
