### ISSUE TITLE
transport::Acceptor starts accepting implicitly

### ISSUE THREAD

**Issue by inetic** [maidsafe/crust#316]
This is incorrect, acceptors should only take ownership of a given port, accepting should be started using the `transport::accept` method.

**Comment by vinipsmaker** [comment]
`transport` module is being refactored currently. I'll report back when it's safe to start implementing this change (or if this change is implemented in the process...).

**Comment by inetic** [comment]
No worries, I just created this issue so that I wouldn't forget it.

Though I just found another issue that would be nice to fix: the `new_acceptor` function no only starts implicitly accepting, it also implicitly binds to a random port if the one given to it is already taken. This is contrary to how any socket library works so I think we should move this "if taken chose random" logic upwards to `crust::Service`.

**Comment by vinipsmaker** [comment]
Okay, I'll solve these issues soon, as [transport was already refactored](https://github.com/maidsafe/crust/pull/319).

**Comment by madadam** [comment]
I think https://github.com/maidsafe/crust/pull/376 also fixes this.

**Comment by vinipsmaker** [comment]
> I think #376 also fixes this.

True =)

Kudos to you, @madadam.

**Comment by vinipsmaker** [comment]
Fixed in #376
