### ISSUE TITLE
crust_peer fails to stop

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#327]
Not the first time it happens ( https://github.com/maidsafe/crust/issues/277 https://github.com/maidsafe/crust/issues/141 ).

**Comment by vinipsmaker** [comment]
It's working again. Not sure which commit fixed it, but must have been work from @inetic.

**Comment by vinipsmaker** [comment]
It's failing again.

## How to reproduce

1. Open a **single** `crust_peer` instance.
2. Do not connect to any other node. You may see:

           Running `target/debug/examples/crust_peer`
           Listening on ports Tcp(V4(0.0.0.0:5483))
           Enter command (stop | connect <endpoint> | send <endpoint> <message>)>

  You might also see:

      Didn't bootstrap to an existing network - this may be the first node of a new network.
3. Enter `stop`.
4. `crust_peer` doesn't stop.

A hint to solve this issue. The hanged/hanging crust_peer instance will gracefully stop if you, now, start another `crust_peer` instance that will automatically connect (through beacon) to the previous instance. This second instance won't have any trouble execute the `stop` command.

**Comment by inetic** [comment]
Fixed here https://github.com/maidsafe/crust/commit/20965f1f6eeaf178572964dba854f97058730677
