### ISSUE TITLE
test `service::test::network` hungs sometimes

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#342]
An example where it fails: https://travis-ci.org/maidsafe/crust/jobs/81865528#L217

It succeed in the same environment/CI-machine in other situations. So it's probably a race.

@inetic's big picture explanation of the test:

> It starts a number of crust::Services, starts listening on each one, then they interconnect such that each one is connected to the other once. Once they are connected, they exchange few messages. The Stats object counts how many messages is exchanged. Once the exact number of messages has been sent, threads will exit and stats merged to see if the numbers correspond.

Start to improving the test by introducing timeouts for each task, then when the timeout fires we know which task is failing. Something [like this might](https://github.com/inetic/crust/blob/ed00ad5738e479668d4be05eb804c4f3a6079c10/src/map_external_port.rs#L142) help. If so, put it in `util.rs`.

**Comment by vinipsmaker** [comment]
As there are multiple `crust::Services` running and there are signs that this problem is caused by a race, I guess the source might be the services fighting over the config/cache files, as they are global resources and easy to cause a race. I'll start investigating now.

**Comment by vinipsmaker** [comment]
We rarely hit this test in our own machines, when we test a new feature, before proposing a pull request. In our machines, we always have config files and cache files from previous runs, so if we didn't spotted the bug locally and end up pushing it to crust master, we have yet another sign that this bug is most likely related to instances fighting over the config/cache files. I'll change the test code to erase these files before doing anything, so we have a higher chance to hit the race (better future-proof too).

**Comment by vinipsmaker** [comment]
On MAC, the test also passes sometimes. Although way less often. So it's easier to test on MAC.

I got 50 consecutive success by keeping the old config/cache files. I couldn't repeat this roll of luck once I started to remove config/cache files before every execution.

A "stable and lucky" (tests pass very often) config file:

```
{
  "tcp_listening_port": 5483,
  "utp_listening_port": null,
  "override_default_bootstrap": false,
  "hard_coded_contacts": [],
  "beacon_port": 5484
}
```

A "stable and lucky" (tests pass very often) cache file: https://gist.github.com/vinipsmaker/e830168bfa753efbaeab

Config file is just the same for failing test. An example of a failure-causing cache file: https://gist.github.com/vinipsmaker/5bc339ad5be888579c51

**Comment by vinipsmaker** [comment]
Even with information about the issue and using this information to increase the failure chance, I didn't manage to reproduce this bug on Linux even once. I'm gonna test it on the OS X.

**Comment by vinipsmaker** [comment]
#347 solves the issue on OS X. Some problem still happens on Windows.

**Comment by Ghaunt** [comment]
I think you make it worst. I do a simple test and the debug output is strange for half or more of the vaults. Maybe the change should be reversed and do some more test before applying it. It's my grain of salt.

**Comment by vinipsmaker** [comment]
@Ghaunt what platform are you using to do the test? Yet Another change was done to fix the issue on Windows. Can you test again with the latest version (0.4.1)?

**Comment by vinipsmaker** [comment]
Fixed by #347 and #348

**Comment by Ghaunt** [comment]
I'm currently testing on Arch-Linux. It's sometimes I didn't test on windows. I pass full days on routing trying to fix bugs because I want it to work correctly. That give me headache. I'm currently close to have a temporary work around.

My best finding so far.
Two node connect together with multiple connection, 2 or 3. One accept the node A with connection X and the other accept the node B with connection Y. So when node A send message to node B. The message pass to node B with the connection X. So node B understand connection X for an unidentified connection. And that is vise versa.

Before updating routing issue I wanted to do more work before.

"You = The teams" for the next statement.
Maybe I should ask. Did you know already about it or if what I'm saying is usefull to you? I got told is going to get fixed at Rust-5.

**Comment by vinipsmaker** [comment]
> My best finding so far. [...]

I'm having trouble trying to understand what is the problem here. Can you elaborate?

**Comment by Ghaunt** [comment]
I updated the issue there with a better output: https://github.com/maidsafe/routing/issues/722
