### ISSUE TITLE
Threads are created exponentially 

### ISSUE THREAD

**Issue by Ghaunt** [maidsafe/crust#346]
Continuing from here: [https://github.com/maidsafe/safe_vault/issues/266](https://github.com/maidsafe/safe_vault/issues/266)

Found a problem with "deferred" here: [https://github.com/maidsafe/crust/blob/master/src/state.rs#L316-L321](https://github.com/maidsafe/crust/blob/master/src/state.rs#L316-L321)
It add the task in the list but if it failed to connect it keep in a list, don't know where and that prevent rust to do a proper cleanup and the thread stay loaded.

For the exponential I found the function is calling himself here: https://github.com/maidsafe/crust/blob/master/src/state.rs#L353

About the bootstrap.cache, if a connection failed, the connection info should be removed from the file?

**Comment by Ghaunt** [comment]
I found this:
https://github.com/carllerche/mio

I don't know if you are aware but if not I just letting you know. It's a crate with the aio ability and it contain the network connection from net2. I would suggest to have a temporary wrapper to that one because it look like it change sometime so it's easy to maintain. That could remove the huge threads amount currently used on large network.

For the asynchronous crate. I would put it in the trash.

**Comment by dpc** [comment]
You might also consider mioco, that would give much more thread-like interface.

**Comment by Ghaunt** [comment]
https://github.com/dpc/mioco
That look very promising.

**Comment by vinipsmaker** [comment]
Take a look at https://github.com/maidsafe/rfcs/pull/63

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
