### ISSUE TITLE
Create a new example

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#353]
The developer should also take the time spent to develop the example and use it to improve documentation by writing a tutorial.

Maybe [an IRC-like client](https://github.com/maidsafe/crust/issues/182).

**Comment by vinipsmaker** [comment]
> For an example it would be nice to see there is two way communications and if possible what connection type we are on (say tcp direct/upnp/utp hole punched) if possible.  In such a way people can run the example from their homes and other places to confirm connectivity as a full node (client node will always be OK I imagine)

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
