### ISSUE TITLE
Add `Service::remove_from_bootstrap_cache(connection)` function

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#354]
Use case:

> Can we notify crust that on a second call to bootstrap, it would not re-establish the same bootstrap connection? (eg doesnt re-open bootstrap cache and starts at the top). The reason is that the bootstrap connection might succeed, but Routing might not validate this connection as a bootstrap connection into the network. We should hence avoid getting caught in a loop of rebootstrapping to the same node. Possibly a "remove_from_bootstrap_cache(connection)"?

-- [Benjamin Bollen](https://maidsafe.atlassian.net/browse/MAID-1383?focusedCommentId=16513&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16513)

**Comment by inetic** [comment]
What about adding another argument to the [Service::bootstrap function](https://github.com/maidsafe/crust/blob/e6fcb63935cb1dbec204498e7c01c7905d0d6b06/src/service.rs#L195) to indicate which endpoints should be avoided when bootstrapping?

**Comment by vinipsmaker** [comment]
> What about adding another argument to the Service::bootstrap function to indicate which endpoints should be avoided when bootstrapping?

I prefer this API you're proposing @inetic, but I think the endpoint should be removed from the cache too.

**Comment by vinipsmaker** [comment]
I just found out this is a duplicate of #220. Not sure which issue to close though.

**Comment by madadam** [comment]
I'm going to make two changes to the API:

1. add an endpoint blacklist to the bootstrap method. This will inform the bootstrap about endpoints which it should not connect to. It won't touch the cache however.
2. add a public `remove_from_bootstrap_cache` method. This will remove the endpoint from the cache.

I think this should cover the use cases described in this issue and also in #220.

**Comment by madadam** [comment]
Number 1 is done: https://github.com/madadam/crust/commit/af343335c54a780cb4043c4e94edbd4db9315186. Number two seems that it can already be achieved (somehow counterintuitively) by calling `BootstrapHandler::update_contacts`:

```
let mut bh = BootstrapHandler::new();
bh.update_contacts(vec![], vec![enpoint_to_remove1, endpoint_to_remove2, ...]);
```

Does it make sense to still add the `remove_from_bootstrap_cache` method to `Service`? It feels to me like we would be violating the separation of concerns a bit. Perhaps adding a more explicitly named method to `BootstrapHandler` would be better idea?

**Comment by vinipsmaker** [comment]
> I think this should cover the use cases described in this issue and also in #220.

@madadam please check with guys from routing if they like this idea.

> Does it make sense to still add the `remove_from_bootstrap_cache` method to `Service`? It feels to me like we would be violating the separation of concerns a bit. Perhaps adding a more explicitly named method to `BootstrapHandler` would be better idea?

I think it still makes sense to add `remove_from_bootstrap_cache`.

**Comment by madadam** [comment]
Ok, PR here: https://github.com/maidsafe/crust/pull/459

**Comment by vinipsmaker** [comment]
PR #459 adds two new functions:

- `Service::bootstrap_with_blacklist(&mut self, token: u32, beacon_port: Option<u16>, blacklist: &[Endpoint])`
- `Service::remove_bootstrap_contact(&mut self, endpoint: Endpoint)`

Need to ask routing guys if they're okay with this API to solve this issue and #220.

**Comment by vinipsmaker** [comment]
Fixed by https://github.com/maidsafe/crust/pull/459
