### ISSUE TITLE
Reporter's logfile excessively large

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#364]
The "reporter" example is intended to be used by QA to interconnect up to 64 nodes, probably for durations of at least several minutes, possibly hours.

However, because there is no throttling of the rate of sending messages in the example, and because we log each individual event, the generated logfiles are unreasonably large.  I tried with just three nodes, each connected to the other two, each with `"service_runs": 10`, and `"max_wait_before_restart_service_secs": 1`.  This resulted in logfiles of around 30MB each (~600,000 lines).

I think there should be discussion with as many team members as possible before deciding on an approach to resolve this, so that the resulting QA test is meaningful and representative of how Crust will be used by Routing/Vaults/Clients.

This is probably not a critical issue, since it's trivial to temporarily modify the example to not output every individual event to the logfile.

**Comment by vinipsmaker** [comment]
> I think there should be discussion with as many team members as possible before deciding on an approach to resolve this, so that the resulting QA test is meaningful and representative of how Crust will be used by Routing/Vaults/Clients.

If we discard events, it'll be less meaningful if we need to investigate problems.

If you only need to run the test without logging anything, just use `/dev/null` as output file.

**Comment by vinipsmaker** [comment]
Fixed by #450
