### ISSUE TITLE
thread 'Service::rendezvous connect' panicked at 'arithmetic operation overflowed'

### ISSUE THREAD

**Issue by inetic** [maidsafe/crust#372]
When trying the `crust_peer` example on two distant computers, where one is behind a NAT and the other one is not, I'm getting an error:

    thread 'Service::rendezvous connect' panicked at 'arithmetic operation overflowed', socket.rs:710

Which is [this line](https://github.com/maidsafe/rust-utp/blob/eece5bee081a47366c238340462ff8a9f5c00524/src/socket.rs#L710).

To reproduce it, build the `crust_peer` example (I'm using commit [a2f0453](https://github.com/maidsafe/crust/commit/a2f04530a0936324c3e71397d0708145d485fc62)) and run it on two distinct PCs `A` and `B`, preferably not on the same LAN, but at least one should be fully visible (not behind a NAT).

On each of them, run the command `map`, this will create a UTP socket and will print its port. Then on node `A` run:

    connect-rendezvous 0 Utp(<IP-of-B>:<Port-of-B>)

and on node `B` run:

    connect-rendezvous 0 Utp(<IP-of-A>:<Port-of-A>)

You should now see the crash.

**Comment by vinipsmaker** [comment]
I update temp_utp crate to get the upstream changes.
