### ISSUE TITLE
`cbor::Decoder<BufReader<utp_connections::UtpWrapper>>` isn't checked after handshake exchange

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#374]
Full explanation: https://maidsafe.atlassian.net/browse/MAID-1431?focusedCommentId=16737&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16737

**Comment by inetic** [comment]
So the crux of the problem is that this line:

https://github.com/maidsafe/crust/blob/master/src/transport.rs#L259
and this line:
https://github.com/maidsafe/crust/blob/master/src/transport.rs#L262

may decode more than one `D`, if that is the case, then only the first one will be returned and all the others decoded in this call will be ignored and destroyed thus never received in `State`.

**Comment by vinipsmaker** [comment]
I'll have to do a few quite intrusive changes to fix this race.

@inetic [originally wanted for `Handshake` to be a separate type in crust](https://github.com/maidsafe/crust/pull/330#discussion_r40177272), as, in his words:

> I think `Handshake` should not be part of the `Message` enum as we'll never send `UserBlob` nor `Contacts` while handshaking and we'll never send `Handshake` while receiving `UserBlob` or `Contacts`.

It happens that we're using the [`cbor::Decoder::decode` function](http://maidsafe.net/crust/master/cbor/struct.Decoder.html#method.decode) to automatically (de)serialize Rust types into CBOR types. However, `cbor::Decoder<BufReader<_>>` don't stop the deserialization once the first fully structured Rust value is extracted. It's not a `next` function or alike. It's more like "get all buffered bytes into a stream of decoded values".

The problem here is that we have two different Rust types, `Handshake` and `Message` and `Decoder::decode` will be confused, as the code will think that all values in the stream should be a `Handshake` once we call `crust::transport::Receiver::receive_handshake`. I predict that the amount of code to (de)serialize the values ourselves using the [`cbor::Decoder::items` function](http://maidsafe.net/crust/master/cbor/struct.Decoder.html#method.items) would add much more maintenance headache and error-prone code than handling the possibility of receiving multiple `Handshake`s. Also, as Rust pattern matching must be exhaustive, we'd get a compile-time error if we don't handle the unexpected `Handshake` value.

So, there are these two options. I'm going to write the `Handshake`-as-a-`Message`-variant solution and push the code to the #366 PR. Doing the code before discussion because the opportunity cost and because I think you'll agree with me. Also, even going for this easier solution will require a few intrusive changes.
