### ISSUE TITLE
service.rs/rendezvous_connect test halts

### ISSUE THREAD

**Issue by inetic** [maidsafe/crust#379]
It is currently unknown where exactly the problem is. It is possible it is in the recently added `rendezvous_connect` function in rust-utp or in Crust itself.

Previously we thought the bug was [here](https://github.com/maidsafe/crust/issues/374) but that was shown not to be the case.

**Comment by vinipsmaker** [comment]
Can we finally close it now? Looks like the bug was in rust-utp.
