### ISSUE TITLE
Add instructions on how to use crust_peer example to rendezvous-connect

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#403]
@inetic gave the following instructions on Slack as to how to use the crust_peer example to achieve a rendezvous-connection:

> 1. Start one instance of crust_peer on a node you know is open to the internet, call this node C
2. Start two crust_peer instances on any PC you want, call them A and B; Connect to C from both of them using TCP.
3. On A and B, call `map`; This will create a UDP socket and it will also try to figure out its external IP.
4. 4.a and 4.b will need to be done simultaneously (think there is 3 sec timeout, we should probably extend this)
   a) On A call `punch 0 <ext-addr-of-B>`
   b) On B call `punch 0 <ext-addr-of-A>`
5. If step 4 succeeds on both nodes, call these commands:
   a) On A call `connect-rendezvous 0 Utp(<ext-addr-of-B>)`
   b) On B call `connect-rendezvous 0 Utp(<ext-addr-of-A>)`
6. If successful, you should now have a connection, you can try sending messages between them using the `send` command.

These instructions need to be added to a README.md file which should be created in the examples folder of this project.

Also, the example should be updated to provide a link to this new page as part of the `help` output.

**Comment by inetic** [comment]
Would this README.md contain information about all the examples? Or just the `crust_peer` one?

**Comment by Fraser999** [comment]
I guess it's best of the examples can explain their own usage via `--help`.  It's just in this case the help output would be unreasonably large.

I haven't checked the other examples to know if they're self-explanatory enough, or if not, whether their help output would be the right place to explain their usage.

**Comment by inetic** [comment]
Another option would be to create a 'sub help'. For example, typing `--help` would tell you there is a parameter `--help-utp-punching` which when used would print out the above instructions.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
