### ISSUE TITLE
crust_peer fails to pick a uTP listening port if the requested port is unavailable

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#406]
If the same crust_peer binary is run twice, and the first instance successfully starts listening on the uTP port specified in the config file, then the second instance can't acquire this port.

If the config file also specifies a TCP listening port, then the second instance listens on a random TCP port, but no uTP listening port is selected.

If the config file doesn't specify a TCP listening port (defines it as `null`) then the second instance crashes with the message:

```
thread '<main>' panicked at 'assertion failed: listening_ports.len() >= 1', examples/crust_peer.rs:441
```

I've labelled this as a bug, because I'd expect the two protocols to behave similarly.  However, if we're not supposed to fall back to a random uTP port, then this is possibly just an enhancement issue to make the tool output a better message to the user before stopping.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
