### ISSUE TITLE
Allow users to explicitly disable beaconing through the config file

### ISSUE THREAD

**Issue by inetic** [maidsafe/crust#413]
As debated, it should work such that when a new config file is created, it would fill the beacon port to the default value (think it is 5483), but users should be able to explicitly set this value to `null` to disable beacon.

**Comment by vinipsmaker** [comment]
> As debated

I tried to find the log of the debate, but I was unsuccessful.

> explicitly set this value to null to disable beacon

I choose an alternative approach of ignoring beacon and assuming the value is `null`.

**Comment by inetic** [comment]
>> As debated

> I tried to find the log of the debate, but I was unsuccessful.

It was in the morning catchup.

**Comment by inetic** [comment]
Reopened because setting `beacon_port` to `null` in the config file gives now this error:

`thread '<main>' panicked at 'beacon_port must be set', src/config_handler.rs:60`
