### ISSUE TITLE
Beacon should only be started explicitly using API, not the config file.

### ISSUE THREAD

**Issue by inetic** [maidsafe/crust#419]
The `Service` object should have a new public member function named `start_beacon(udp_port: u16) -> io::Result<u16>`, beacon should not be started implicitly through `Service::new` and any mention of beacon should be removed from the config file structure.

The tricky part about this task is that since beacon acceptor was previously created in the constructor, its presence was used as an indicator whether we can write into the bootstrap.cache file or not. Since we no longer can rely on it, we need other means to ensure our bootstrap.cache file doesn't get corrupted (written to by multiple processes).

Here is some brain dump of alternatives:

1. Use actual database
2. Use memory mapped files to sync file access between processes
3. Create a thread that will accept connections on a predefined TCP port, only one process per PC can successfully start such acceptor. Only the process with the acceptor can access the cache file, and all the other processes will need to communicate changes to the file through TCP connections.
4. All processes shall first write to a unique temporary files, once done, the temporary files will be renamed to the bootstrap.cache file.

**Comment by dirvine** [comment]
:+1 for 2: as this seems the correct answer

**Comment by vinipsmaker** [comment]
`1.` seems correct answer, but I didn't see a `SQLite` or alike for Rust. I also don't think it's correct to wait 5 years until somebody write one. `3.` is hacky and inconvenient. So I'd vote on `2.` .

**Comment by vinipsmaker** [comment]
Previously we're only accepting the possibility to start beaconing once. Should we change that now?

**Comment by vinipsmaker** [comment]
Solved in #422
