### ISSUE TITLE
Service::stop should either be made private or take self by value

### ISSUE THREAD

**Issue by madadam** [maidsafe/crust#469]
`Service::stop` leaves the service in unusable state. So it should either be private, so users can't call it (they should drop the service instead), or it should take `self` by value, so the compiler makes sure the service is not used after calling it.

**Comment by vinipsmaker** [comment]
I vote to make it private

**Comment by madadam** [comment]
Yeah, me too. I'll post a PR shortly.

**Comment by madadam** [comment]
[PR](https://github.com/maidsafe/crust/pull/471)

**Comment by vinipsmaker** [comment]
Fixed by #471
