### ISSUE TITLE
filter out unspecified addresses from `StaticContactInfo`

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#534]
https://ci.appveyor.com/project/MaidSafe-QA/crust/build/1.0.772/job/x439y9t2ebcidmhm#L603

Just in case a CI rebuild screw up the previous URL, I'm also posting an image (I tried to create a PDF using wkhtmltopdf, but it didn't work):

![captura de tela_2016-02-17_09-29-13](https://cloud.githubusercontent.com/assets/865914/13109613/27276e32-d559-11e5-9618-d78904e6de80.png)

**Comment by canndrew** [comment]
That should never happen, it might be a bug in nat_traversal.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
