### ISSUE TITLE
Add ability to blacklist certain peers from bootstrap

### ISSUE THREAD

**Issue by madadam** [maidsafe/crust#535]
Possibly add a `blacklist: Vec<PeerId>` parameter to the constructor: `Service::new(sender, beacon_port, blacklist)`

This feature is important for routing, to be able to retry bootstrap while blacklisting peers we unsuccessfully tried to bootstrap against previously.

**Comment by madadam** [comment]
@afck Does Routing still need this?

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
