### ISSUE TITLE
Send only one `NewPeer` per peer.

### ISSUE THREAD

**Issue by afck** [maidsafe/crust#539]
Make sure Crust sends only one `NewPeer` event per peer.
I already partially implemented this for the TCP-only version: https://github.com/afck/crust/commit/24f34d237b2549a0223e347f4486ba24c4b02337

**Comment by vinipsmaker** [comment]
> I already partially implemented this for the TCP-only version: https://github.com/afck/crust/commit/24f34d237b2549a0223e347f4486ba24c4b02337

Merged PR: https://github.com/maidsafe/crust/pull/541

**Comment by vinipsmaker** [comment]
Fixed in https://github.com/maidsafe/crust/pull/553
