### ISSUE TITLE
Check peer keys on connect.

### ISSUE THREAD

**Issue by afck** [maidsafe/crust#540]
I already partially implemented this for the TCP-only version:
https://github.com/afck/crust/commit/df9b69871dc65508a2d1cf26a7f8df9e9a4f108c

**Comment by vinipsmaker** [comment]
> I already partially implemented this for the TCP-only version:
https://github.com/afck/crust/commit/df9b69871dc65508a2d1cf26a7f8df9e9a4f108c

Merged in https://github.com/maidsafe/crust/pull/541

**Comment by vinipsmaker** [comment]
Fixed in https://github.com/maidsafe/crust/pull/554
