### ISSUE TITLE
Test for random connection loss

### ISSUE THREAD

**Issue by Viv-Rajkumar** [maidsafe/crust#569]
Can we please get a new test in crust which can:

spawn a listening node(beacon node)
spawn about 5 clients that bootstrap against the listening node
In parallel: each client sends the beacon node 1000 messages in a short span
assert beacon node receives all messages sent by the client nodes.

Currently as identified by @maqi vault tests seem to show nodes sometimes dropping connections to peers when handling some traffic. Hope here is to have this test confirm this isn't a crust issue.

**Comment by madadam** [comment]
PR: https://github.com/maidsafe/crust/pull/570

**Comment by vinipsmaker** [comment]
https://github.com/maidsafe/crust/pull/570 merged
