### ISSUE TITLE
Crust doesn't include acceptor ports in connection info.

### ISSUE THREAD

**Issue by afck** [maidsafe/crust#588]
I enabled port forwarding in my router and set that port as both `tcp_acceptor_port` and `utp_acceptor_port` in the config file. We also had working mapper servers enabled for both. However, only my local IP addresses showed up with the forwarded port in the connection info, but not the external one.

**Comment by afck** [comment]
The problem seems to be that my router chooses a new external port for every outgoing connection, even if I forward 7000 to 7000 and use that port for sending data to the mapper server. So the mapper server never even gets the information that it should try connecting to me on port 7000.

This could probably either be solved in nat_traversal by telling the mapper server to try a specific port in addition to the one it got the message from (that would verify that port forwarding is configured correctly), or in Crust, by just always adding that port to the endpoints.

**Comment by afck** [comment]
As discussed, we will go with the quick solution in Crust for now: Always add to the endpoints all our IP addresses together with the acceptor port.

**Comment by canndrew** [comment]
r? @canndrew

I'll fix this tomorrow morning.

**Comment by canndrew** [comment]
This should be fixed now @andreas, can you confirm that it works on your router?

**Comment by afck** [comment]
I will verify it in April, when I'm behind that router again.
