### ISSUE TITLE
NewPeer should never be sent before connect was called.

### ISSUE THREAD

**Issue by afck** [maidsafe/crust#589]
If one peer is directly reachable and the other peer calls `crust::Service::connect`, a connection will be established and a `NewPeer` event raised on both sides. This should only happen after _both_ sides have called `connect`.

**Comment by madadam** [comment]
Is there a reliable way to reproduce this bug? I tried to write a test case for it, but it passed.

**Comment by afck** [comment]
If I `prepare-connection-info` on both sides in the crust_peer example, but then call `connect` on only one side, I get a connection, and I get the event on both sides.

**Comment by madadam** [comment]
Confirmed. Failing test case here: https://github.com/madadam/crust/blob/spurious-new-peer-event-fix/src/service.rs#L1115

**Comment by canndrew** [comment]
Fixed in #608
