### ISSUE TITLE
Bootstrap gets stuck if there is an invalid UDP contact in the crust config file or the bootstrap cache

### ISSUE THREAD

**Issue by madadam** [maidsafe/crust#595]
Steps to reproduce:

- create crust config file whose hard_coded_contacts field contains an invalid UDP contact (you can use 192.0.2.0, which is a documentation-only IP address which nobody should listen on.)
- create a service and make it use this config file
- wait for `Event::BootstrapFinished` from this service.
- you are going to wait forever :cry: 

The problem could possibly be fixed by setting a read timeout on the UDP socket.

**Comment by canndrew** [comment]
@madadam was this fixed in #608?

**Comment by vinipsmaker** [comment]
> @madadam was this fixed in #608?

I believe it was. If I'm not mistaken, this is the line changed that should fix the problem: https://github.com/maidsafe/crust/pull/608/files#diff-c80c453b374ae714374e0f9d9d86ba1cR193

**Comment by madadam** [comment]
Yes, should be fixed. Closing.
