### ISSUE TITLE
Add option to either bypass bootstrap cache or override its location

### ISSUE THREAD

**Issue by madadam** [maidsafe/crust#600]
The bootstrap cache interferes with multithreaded testing: Sometimes a service in thread A creates the bootstrap cache and service in thread B reads it and tries to bootstrap against it. B then ends up bootstrapping against A, which causes non-deterministic test failures.

Current workaround: force `RUST_TEST_THREADS=1`. Not nice as it makes the test slower.
Possible fix: Add option to disable bootstrap cache (at least in tests)
Another possible fix: Add option to override the location of the cache file. Then each test could set it to a unique, temporary file.

**Comment by canndrew** [comment]
Fixed in #609
