### ISSUE TITLE
Not raise `NewPeer`/`LostPeer` for ourselves

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#605]

**Comment by afck** [comment]
We were seeing this with both Crust 0.9.0 and with the current master, running vaults on droplets. A routing trace statement printed both the `NewPeer` event we had received with our own peer ID, and the `LostPeer` event.

**Comment by vinipsmaker** [comment]
It should be fixed in https://github.com/maidsafe/crust/pull/616
