### ISSUE TITLE
Clarify license situation

### ISSUE THREAD

**Issue by infinity0** [maidsafe/crust#630]
Hi, could you please clarify, in README.md (or in some other top-level obvious place) what license this software is released under? The LICENSE and COPYING file contains two contradictory licenses.

I see that in source files you have the text "This SAFE Network Software is licensed to you under [commercial] or [GPL] depending on which licence you accepted". Please note that this is inappropriate wording - the GPL is **not** an "end-user license agreement" and does not require the user to "agree" to it. You just say "we release this work under GPL". One agrees to be bound by the GPL when one releases one's own modified version; before this event there is no "agreement" to be done - the parts of the GPL active before this event are all *unconditional grants of permission*.

Generally in FOSS projects, COPYING is a file describing what your license terms are; LICENSE.* are standalone text files that describe a set of terms without reference to your project. If you like, you can think of COPYING as explicitly binding LICENSE.* plus explicit other terms to your project. For this project, COPYING should say something like "crust is licensed under GPL-3, or if you paid for it then (at your option) either GPL-3 or the commercial license." You would put the text of the commercial license in LICENSE.Commercial or something.

**Comment by dirvine** [comment]
This sound reasonable, I don't see any issue with this and it may make it more clear. Thanks for the feedback, license feedback is generally so debatable and this is refreshing.

**Comment by vinipsmaker** [comment]
Well, I agree with everything you said and we should pursue it. Gonna wait for other members to reply. However...

> Please note that this is inappropriate wording - the GPL is **not** an "end-user license agreement" and does not require the user to "agree" to it.

This is only true for using GPL-licensed software. You still need to agree to the license if you intend to share it. You must agree to share the work under the same license.

For usage you're correct though.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
