### ISSUE TITLE
VPN service access

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/crust#684]
From Anonymous user:

> We use privateinternetaccess VPN service at the router level. All outbound LAN traffic goes through the VPN tunnel.
> The SAFE launcher does not connect through the VPN.
> It is always trying to connect.
> I assume it would have the same problem through TOR.
> 
> Does MaidSafe require access to the physical IP through a specific port?
> This is consistent with devices like PogoPlug.
> This is probably required for any point on the network to connect to my system.
> 
> What is the answer here?
> 
> It appears that I need to set our router to bypass the VPN tunnel for all TCP traffic for the local IP address, both as a source and destination, of the PC running MaidSafe. Based on the firewall settings, there is no specific external source IP address or external destination IP address, but it seems it will only be TCP traffic. Also, there are no specific port numbers used for MaidSafe connections. While the MaidSafe connections are kept private to some extent, the ISP will still see the local nodes being connected. However, this only provides reasonable security when using the SafeNet. All other traffic is exposed to the ISP.
> 
> It is obvious that the external (local group) connection IP addresses could be almost anything and could change regularly, the ports used could be limited. This would at least not require all internet traffic to go through the ISP naked.
> 
> Do I understanding this correctly?
> Is the only solution to not use the VPN tunnel for all IPs and Ports for TCP traffic to and from the PC running MaidSafe?
> 
> Thanks.

**Comment by wtw2** [comment]
I believe I found my biggest problem; the SAFEnet does not appear to be always running yet.

Is there a schedule when it is running for testing?
I would like to create an account.
Thanks,
wtw2

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
