### ISSUE TITLE
more test code to see if message prioritisation is functioning properly

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#768]
Guarantees/properties that message prioritisation needs to maintain:

> 1. Priority 0 should never be dropped
> 2. for rest if msg is expired, drop all subsequent messages in all subsequent queues (even if the subsequent queues have msgs that haven't yet expired)

**Comment by ustulation** [comment]
I have put it as a TODO. Removing it as an issue. Currently on Issues-Purging-Spree :)
