### ISSUE TITLE
Mio deprecated APIs

### ISSUE THREAD

**Issue by ustulation** [maidsafe/crust#837]
All deprecated miio apis seem too be dumped into [mio-more crate](https://github.com/carllerche/mio-more/tree/0fdf0024756acf12d204e2a98aea04fb7bbcde09) which looks very undocumented and not-maintained a.t.m. So track that to [remove this linter](https://github.com/maidsafe/crust/blob/ffe94e8849340c98f97729c4aa4c381cf3cc59e2/src/lib.rs#L41) and provide proper solution with latest mio.

cc @nbaksalyar @madadam

**Comment by povilasb** [comment]
Is this deprecated since we started using Tokio?

**Comment by povilasb** [comment]
We will be using mio based Crust implementation for SAFE net alpha-3 so this is still relevant and work is in progress.
