### ISSUE TITLE
It becomes increasingly slow to connect a node to an example network

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#85]
When running a testnet of nodes running `crust_node` example, it becomes increasing slow to connect a new node to the network.

My suspicion is that the bootstrap list being returned by the beacon node is growing ever larger (and can contain permanently dead nodes from previous runs) and we're attempting to connect to these listed nodes sequentially.

**Comment by Fraser999** [comment]
While I've not really looked at this issue, I have noticed on my travels through Crust that my suspicions above appear to be correct.  A failed connect attempt can block for anything from 2 to ~20 seconds.

Issue #91 is also related to this.

A simple change which could perhaps help is to reverse the order of the bootstrap list so that the most recently-seen endpoint is tried first.

**Comment by vinipsmaker** [comment]
Can you test now that #330 got merged (and a lot of other refactors happened too)? I think we could achieve some speedups by increasing [`ControlFlow::ParallelLimit`](https://github.com/maidsafe/crust/blob/9a8a11589076dcbf6d1e0900a56eb68bc43516c2/src/state.rs#L308), but I still need to investigate.

**Comment by vinipsmaker** [comment]
Obsolete.
