### ISSUE TITLE
Don't call rendezvous_connect if we know we have an accessible listener.

### ISSUE THREAD

**Issue by canndrew** [maidsafe/crust#889]
Currently, crust will always call rendezvous_connect from the p2p crate when doing a rendezvous connect. However we don't need to do this if we know we have a publicly-accessible open port.

Some things to consider:
  * We need to make sure that p2p doesn't return false positives about when a port is publicly-accessible.
  * We need a way to make sure that the port on the router stays open.

**Comment by povilasb** [comment]
This was implemented some time ago,
