### ISSUE TITLE
We add all connections to the bootstrap list

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#91]
It looks like we unconditionally add peer TCP endpoints to the bootstrap list, even though the remote end may not be a TCP listening endpoint and will be unable to accept new connections.

**Comment by dirvine** [comment]
Ah that's not good.

**Comment by Viv-Rajkumar** [comment]
that might explain #85 to some extent?

**Comment by vinipsmaker** [comment]
Now we have a custom Crust handshake and [we already have some "filters" to bootstrap list (given the issue description) for some time](https://github.com/maidsafe/crust/blob/d9aa489cc4ef84d0557c983c50650334cbd52141/src/state.rs#L169). Can I mark the issue as closed?

**Comment by Fraser999** [comment]
If the filtering means we're now only adding contacts who we'd be able to bootstrap off (assuming their endpoints don't change), then yes, please close this.
