### ISSUE TITLE
Use correct bootstrap order

### ISSUE THREAD

**Issue by canndrew** [maidsafe/crust#913]
When bootstrapping, make sure we try to connect to service-discovery peers first, then bootstrap cache peers, then hard-coded contacts. Also make sure that groups of peer addresses are shuffled.

**Comment by povilasb** [comment]
https://github.com/maidsafe/crust/pull/923 covers the service discovery and hard-coded contacts. Make sure we come back to this issue when bootstrap cache is implemented.

**Comment by povilasb** [comment]
This was implemented a while ago.
