### ISSUE TITLE
Bootstrap method should return multiple connected endpoints

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/crust#92]
Crust's bootstrap method should try to connect to multiple endpoints discovered from multiple sources (responses from multiple beacon listeners and also local bootstrap.cache file).
This means the crust bootstrap method should return vector of *n* endpoints it is connected to.

Details :

If there are X Beacon servers in a LAN and each one of them return Y bootstrap endpoints,
CRUST needs to return after validating each endpoint can be successfully connected a maximum of either X * Y connected endpoints(provided all Y endpoints returned by each beacon server are valid) or introduce a filter to limit connections per beacon server / total returned to the consumer of this library.
(same applies for endpoints from local bootstrap.cache file and any further sources we support in crust library) 

**Needs to be decided: (should 'n' be definable? and if so by which of the following approaches)** Allow consumer of this lib to either specify filter based on cap connections per beacon server / total capped connections returned by CRUST / no filter

**Comment by dirvine** [comment]
I vote the user of the lib should set this on construction of a crust object. It's an important security issue and what gets returned is up to this limit (as early nodes may not have many connections to get) and where we think we have X poss connections and we want Y (set by user) we should ensure the number form beacon alone are limited and prefer bootstrap cache nodes. The use of the lib will prob ask these be disconnected when they have their own connections anyway.

**Comment by Viv-Rajkumar** [comment]
Pausing this task for now. We will address it at the end of the current iteration since this will also likely involve updates spanning other libraries(routing) and also updates in various places of this lib.
