### ISSUE TITLE
Bootstrapping connections, info exchange and multicast

### ISSUE THREAD

**Issue by et4te** [maidsafe/crust#955]
Hey there,

Trying to get nodes communicating and ran into a few issues after trying to get somewhere past the examples.

* Without copy & pasting public connection information, how do two nodes prepare the connection in order to connect? I've tried adding bootstrap contacts which when doing bootstrap_accept() / bootstrap() get a 'peer' structure in the Future - splitting this into sink / stream and doing send or receive from either end doesn't seem to work.

* What is the expected way to do multicast? I can't seem to find any code which does this in the repo but maybe I'm blind.

**Comment by et4te** [comment]
Fixed the first issue doing this on the bootstrap node:

```rust
        println!("Spawning bootstrap acceptor .");
        handle.spawn(
            service
                .bootstrap_acceptor()
                .for_each(|peer| {
                    let (peer_sink, peer_stream) = peer.split();
                    peer_stream
                        .for_each(|data: Vec<u8>| {
                            println!("Received: {}", unwrap!(String::from_utf8(data)));
                            Ok(())
                        })
                        .then(|_| Ok(()))
                    // Ok(())
                })
                .then(|_| {
                    Ok(())
                }),
        );
```

And this on a regular node:
```rust
        let bootstrap_peer: Peer<NodeId> = unwrap!(
            event_loop.run(
                service.bootstrap(
                    HashSet::new(),
                    service_discovery,
                    CrustUser::Client,
                )
            )
        );

        let (peer_sink, peer_stream) = bootstrap_peer.split();

        println!("Sending hello ...");
        unwrap!(
            event_loop.run(
                peer_sink
                    .send((1, format!("hello").into_bytes()))
                    .and_then(|peer_sink| {
                        println!("Sending ok ...");
                        peer_sink.send((1, format!("ok").into_bytes()))
                    }),
            )
        );
```
So it seems as if bootstrap connections are already connected and you can just send / receive.

**Comment by povilasb** [comment]
Hey, Edward, indeed, when we're bootstrapping from some node, Crust uses hard coded contacts. These contacts have d is their public address and public key which is all we need to securely connect to some peer. So no connection info is required and it is not exchanged later. But note that we can bootstrap only from publicly accessible nodes - no hole-punching is executed in this case.

Multicast is out of scope of Crust. Crust has no sense of network, it only deals with two peer communication. 
Could you tell a bit about your usecase?

**Comment by ustulation** [comment]
We have peer-discovery over LAN which uses broadcast (ServiceDiscovery) anyway

**Comment by et4te** [comment]
> Hey, Edward, indeed, when we're bootstrapping from some node, Crust uses hard coded contacts. These contacts have d is their public address and public key which is all we need to securely connect to some peer. So no connection info is required and it is not exchanged later. But note that we can bootstrap only from publicly accessible nodes - no hole-punching is executed in this case.

Thats good information, thanks.

> Multicast is out of scope of Crust. Crust has no sense of network, it only deals with two peer communication. Could you tell a bit about your usecase?

Sure, I'm basically experimenting with a leaderless consensus model. Some of the operations in the model require multicast in the sense of having an operation that can just send data across all active connections. I'm using a basic kademlia router (custom) at the moment for node discovery and acquiring a set of active connections. From there theres the naive way of just looping across the connections and sending some data but I'm trying to get away from that - ideally a multicast primitive in Crust could have been used which sends data to N active connections simultaneously. Barring that I might try something like mpsc crossbeam or investigate further down that path.

**Comment by povilasb** [comment]
yeah, Crust doesn't keep a list of alive connections. You have to manage them yourself. But probably it shouldn't be too hard to implement a multicast function :)
