### ISSUE TITLE
failed to select a version for `byteorder`

### ISSUE THREAD

**Issue by LEXUGE** [maidsafe/crust#956]
when I try to compile this lib, I've got:
```
all possible versions conflict with previously selected versions of `byteorder`
required by package `bincode v0.8.0`
    ... which is depended on by `maidsafe_utilities v0.15.0`
    ... which is depended on by `lib_shadowchain v0.1.0 (file:///home/lexuge/Documents/Rust/lib_shadowchain)`
  previously selected package `byteorder v1.1.0`
    ... which is depended on by `crust v0.30.0`
    ... which is depended on by `lib_shadowchain v0.1.0 (file:///home/lexuge/Documents/Rust/lib_shadowchain)`
  possible versions to select: 1.2.2
```
What's up?

**Comment by LEXUGE** [comment]
I'm using the `Crust` from the crates.io

**Comment by povilasb** [comment]
Ok, well, that's quite outdated and you really wanna consider dev branch instead: https://github.com/maidsafe/crust/tree/dev - it's Tokio/Futures based implementation which is way more modern.

Anyway, if tha's not smth you're looking for, could you post your `Cargo.toml`? Possibly your project has a conflicting `byteorder` crate version with the one used by Crust `0.30.0`

**Comment by Bombfuse** [comment]
I'm also having this issue, did you find a solution? @LEXUGE

**Comment by LEXUGE** [comment]
> I'm also having this issue, did you find a solution? @LEXUGE

Nope

**Comment by povilasb** [comment]
Could you guys try to use the latest commit from the master branch? Personally, I'm not seeing this error anymore. 
Also, once we are done with the https://github.com/maidsafe/crust/projects/2 we will be publishing a new version on crates.io as well :)

**Comment by LEXUGE** [comment]
> Could you guys try to use the latest commit from the master branch? Personally, I'm not seeing this error anymore.
> Also, once we are done with the https://github.com/maidsafe/crust/projects/2 we will be publishing a new version on crates.io as well :)

Sorry, I'm no longer using crust. so I'll close this issue.
