### ISSUE TITLE
Reliable connections

### ISSUE THREAD

**Issue by et4te** [maidsafe/crust#957]
Expanding from the example code, let us suppose we are connecting to a bootstrap node.

We can use e.g:

```rust
        let bootstrap_peer: Peer<NodeId> = unwrap!(
            event_loop.run(
                service.bootstrap(
                    HashSet::new(),
                    service_discovery,
                    CrustUser::Client,
                )
            )
        );

        let (peer_sink, peer_stream) = bootstrap_peer.split();

        let (sender, receiver) = bi_channel::unbounded();

        let sub_handle = handle.clone();

        let exchange_info = receiver.into_future()
            .and_then(move |(this_ci, receiver)| {

                let ci: PubConnectionInfo<NodeId> = unwrap!(this_ci);
                let ci_str = unwrap!(serde_json::to_string(&ci));

                // Send our info to the peer
                let mut send_ci = peer_sink.send((1, ci_str.into_bytes()))
                    .then(|_| Ok(()));

                let mut recv_ci = peer_stream
                    .for_each(move |data: Vec<u8>| {
                        let ci_str = unwrap!(String::from_utf8(data));
                        let ci: PubConnectionInfo<NodeId> =
                            unwrap!(serde_json::from_str(&ci_str));

                        // Send ourselves the received peer info
                        // This fails 1/2 the time due to receiver disappearing
                        let r = receiver.unbounded_send(ci);
                        match r {
                            Ok(_) => Ok(()),
                            Err(err) => {
                                println!("err = {:?}", err);
                                Ok(())
                            },
                        }
                    })
                    .then(|_| Ok(()));

                // Using sub_handle.spawn here or unwrap!(recv_ci.poll()) fails as well
                let remote = sub_handle.remote();

                remote.spawn(|_| send_ci);
                remote.spawn(|_| recv_ci);

                Ok(())
            })
            .then(|_| Ok(()));

        handle.spawn(exchange_info);

        let connect = service.connect(sender)
            .map(move |peer| (peer, service));

        let (peer, service) = unwrap!(event_loop.run(connect));
```

Around 50% of the time (randomly) this will produce a SendError(...) in the unbounded send due to a race condition. The error has no detail apart from "..." so I assume the receiver is being dropped. Since this is essentially the most basic example of connecting to a bootstrap peer and exchanging connection information, how can you make a reliable connection with crust dev branch?

**Comment by povilasb** [comment]
You should get `SendError` not when the `receiver` is dropped, but when the `sender` is. And seems like the `sender` is dropped after last statement:
```
 let (peer, service) = unwrap!(event_loop.run(connect));
```
Also, you shouldn't be sending connection information more than once through the channel. But it seems like that's not the case in your example, cause you're sending connection info `let r = receiver.unbounded_send(ci);` every time you receive something from peer: ` .for_each(move |data: Vec<u8>| {`.

Anyway, besides that, your example looks really unusual. I can't understand what you're trying to achieve. It seems like

1. you're bootstrapping to some peer
2. you send our connection info to this peer
3. you're again trying to connect to the same peer?

If I got it right, you don;t need to call `connect()` anymore. Once, `bootstrap()` returns you `Peer`, that's it, you can communicate with it. So you either use `connect()` or `bootstrap()`, but not together.

**Comment by et4te** [comment]
The sender is not dropped though, there is a loop afterwards which calls event_loop.turn(Some(duration)) but omitted the code for brevity. If you look at the futures::mpsc docs the SendError is described as follows: 

> Error type for sending, used when the receiving end of the channel is dropped

> Also, you shouldn't be sending connection information more than once through the channel.

It is not sending it more than once through the channel. 

> Anyway, besides that, your example looks really unusual. I can't understand what you're trying to achieve.

The only way in the library as far as I can see to get hold of your PubConnectionInfo is by sending it through a bi_channel in a 'service.connect' call. If you need to store PubConnectionInfo (since its the only thing that is serializable in the lib pretty much and that can be stored and used later to connect to peers) you can't get this after bootstrapping without doing a next connect call. So maybe the larger issue is simply, why isn't PubConnectionInfo publically available from a received Peer struct?

In any case, since it is not accessible directly in the peer structure the solution above connects and sends the connection information - it is afaik the only way to do it without rewriting crust. I hope this clarifies the extremely simple intent behind my 'unusual' example.

**Comment by povilasb** [comment]
Hmm, why do you want to hold `PubConnectionInfo` though? `PubConnectionInfo` is very temporary per connection session. It includes hole punching information which won't make any sense after some time passes...
Also, I'd like to note that the structure used to be available publicly, but we intentionally changed `Service::connect()` interface so that you wouldn't need to deal with that...

**Comment by et4te** [comment]
> Hmm, why do you want to hold PubConnectionInfo though? PubConnectionInfo is very temporary per connection session. It includes hole punching information which won't make any sense after some time passes...

The goal is to be able to cache the contact information such that it can be referred to later or e.g used to re-connect to the same contact. When you establish a connection you call service.connect(...) which requires a PubConnectionInfo to be sent down a bi_channel. If this was not necessary then there would be no need for PubConnectionInfo to be retained. For example if it was possible to do service.connect(address) then none of this would be necessary but that is not the API being exposed as Service. 

Perhaps this is not in the design of crust. I'm going to be switching to using tokio instead so feel free to close this issue if you consider it solved.

**Comment by povilasb** [comment]
In that case Crust caches the peers it successfully connected to. There's this `bootstrap::Cache` for this: https://github.com/maidsafe/crust/blob/dev/src/net/peer/connect/bootstrap/cache.rs
It will store cached peers on disk and will reuse them next time you're trying to bootstrap.

Note, that peer addresses are very dynamic. Usually Crust peers will have random ports, they also have public encryption key, so in many cases `service.connect(address)` wouldn't work as expected. And since there are a lot of technical details, we try to leak as less as possible of those. 

I'm very interested if there's a case we still haven't covered though. Does bootstrap cache solve your problem?

**Comment by et4te** [comment]
The first comment I would make about this cache is why is it called a bootstrap cache. Bootstrap cache makes it sound like bootstrap is the only time it is applicable. 

> Note, that peer addresses are very dynamic. Usually Crust peers will have random ports, they also have public encryption key, so in many cases service.connect(address) wouldn't work as expected. And since there are a lot of technical details, we try to leak as less as possible of those.

Indeed but there has to be a way of managing this dynamic set of addresses outside of a static view, which is what it seems the bootstrap cache provides at this moment. It doesn't help with the dynamic behaviour of the connections afaict. Without being able to initiate direct connections and having little control over the dynamic behaviour that the cache instigates makes it pretty tricky to use the library. Bare in mind the cache is hidden away in a bootstrap module and it certainly wasn't clear that this cache was meant to be interfaced to from docs and examples.

> I'm very interested if there's a case we still haven't covered though. Does bootstrap cache solve your problem?

With some extensions the cache might be usable for my purposes, though it doesn't include functions to make it easy for the cache or its entries to be transferred between peers afaict.

**Comment by povilasb** [comment]
> Bootstrap cache makes it sound like bootstrap is the only time it is applicable.

Indeed it is, this cache is only used by [bootstrap()](https://github.com/maidsafe/crust/blob/dev/src/net/peer/connect/bootstrap/mod.rs#L54).

Probably we could easily make `Service` bootstrap cache accessible: https://github.com/maidsafe/crust/blob/dev/src/service.rs#L246
What would you say, @canndrew ?

Thanks, @et4te , will update the docs :)

**Comment by canndrew** [comment]
My thoughts are that crust's API is not well-designed, as @et4te is noticing. There's plenty of reasons beyond bootstrapping why someone might want to make a direct connection, and storing the list of known endpoints should really be the responsibility of the application, not a low-level library. Also `PubConnectionInfo` is an implementation detail which should be hidden so people don't try to use it.

I would like to re-skin crust so that is looks something like this:

```rust
impl Service {
    pub fn direct_connect(&mut self, addr: PeerAddr)
        -> impl Future<Item = Peer>;

    pub fn direct_connect_all<A: Iterator<Item = PeerAddr>>(&mut self, addrs: A)
        -> impl Stream<Item = Peer>;

    pub fn rendezvous_connect<C: AsyncRead + AsyncWrite>(&mut self, channel: C)
        -> impl Future<Item = Peer>;
}

impl Peer {
    pub fn static_addr(&self) -> Option<PeerAddr>;
}
```

Then the user could easily collect the static addresses of any peers they connect to and pass them back in through `direct_connect_all` when they want to bootstrap. We could make a library for persisting/updating a set in a file and the user could plug that into crust with only a couple of lines of code to reimplement the current bootstrapping behaviour.

**Comment by povilasb** [comment]
We are discontinuing the `dev` branch, so I'm closing this issue. Anyway, thanks guys for the thoughts.
