### ISSUE TITLE
Make tests::netsim::rendezvous_connect_over_poor_connection pass reliably

### ISSUE THREAD

**Issue by canndrew** [maidsafe/crust#959]
This test can sometimes fail. This needs to be investigated.

**Comment by canndrew** [comment]
This seems to be due to: https://github.com/canndrew/tokio-utp/issues/12

**Comment by povilasb** [comment]
This is only relevant to Crust dev branch whose development has been paused. We're also not using netsim anymore to reduce the scope of the tools we support.
