### ISSUE TITLE
Make tests::compat_api::bootstrap_using_service_discovery pass reliably

### ISSUE THREAD

**Issue by canndrew** [maidsafe/crust#960]
This test can sometimes fail. This needs to be investigated.

**Comment by povilasb** [comment]
The problem with this test is that it uses the default service discovery port:
* https://github.com/maidsafe/crust/blob/dev/src/tests/compat_api.rs#L290
* https://github.com/maidsafe/crust/blob/dev/src/tests/compat_api.rs#L66

So if there are any other service discovery tests and they probably use the same port, those tests interfere.

**Comment by povilasb** [comment]
This is only relevant to Crust dev branch whose development has been paused. In addition, I believe this issue was already fixed.
